### ISSUE TITLE
TE-102: Question additional attributes

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#102]
Estimated Time: 2 days
Actual Time: -

To add more fields to Questions entity:

- Objective - (Textarea)
- Bloom Classification (http://www.nmmu.ac.za/cyberhunts/bloom.htm) -(Select list with following options [Knowledge, Comprehension, Application, Analysis, Synthesis, Evaluation])
- Difficulty Level - (Select list with following options (1,2,3,4,5,6,7,8,9,10)
- Metadata - (Textarea)

**Comment by babanesma** [comment]
@badr4php please check my comments in https://github.com/camelcasetechsd/testing-engine/commit/bb9c02e24486e8c4e58331ba64a5a66cbe7e2a21
