### ISSUE TITLE
TE-106: Test Proctor to Approve Test Taker Details

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#106]
Estimated Time: 1 days
Actual Time: -

- For non practice exams, the Test Proctor has to approve test taker details (implemented in Desktop app but not yet in web app).

**Comment by babanesma** [comment]
@AbdElmoneimMohamed please check my comments in https://github.com/camelcasetechsd/testing-engine/commit/eb79dfbe1b7b613863ae5ef3cb1edbc045439cc9
