### ISSUE TITLE
TE-115: SPIKE - Check all modules inactive records issue

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#115]
Estimated: 1 hour
Actual: -

Currently whenever we disable a records (soft delete) then try to edit/view that record it returns error page.
This issue fixed separately in Labs CRUD TE-22, but we need to check the rest of modules to make sure the issue is not repeated elsewhere.

**Comment by AbdElmoneimMohamed** [comment]
after this spike i found that some models when Deactivate an entity :
   * we remove the edit link from the index page   for this entity
   * the edit link appear but the edit page give error
   * the edit link appear and the edit page don't give error  but when save our update it's make error

So, i will list the models which it make this errors

model     edit link disappere   edit page display error   save our update display error   additional errors

users                  true                           true                                     true                               view page

roles                   true                           true                                     true                               privileges page

testingCenter                             		                                       true                                view page 

reports                                                                                            true                      

QuestonType       true                           true                                   true                                  delete link

Setting                 true                           true                                    true

Tests                    true                                                                      true                      

Questions           true                            true                                     true                         model answers link

category             true                                                                        true                         

provider             true                             true                                       true

**Comment by badr4php** [comment]
- [x] If test was deactivated and you  try to deactivate model answers ,its return error 
![deactivate-modelanswer](https://user-images.githubusercontent.com/24792169/29003521-ac82b8f6-7ab8-11e7-93d0-a9494a624d5d.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/123

**Comment by solimansamy** [comment]
@badr4php Please check the following cases

- [x] When create a question for inactive test.
- [x] When create a model answer for inactive question.

**Comment by badr4php** [comment]
PR  : https://git.camelcasetech.com/camelCase/testing-engine/pulls/127
