### ISSUE TITLE
TE-120:  Ordering Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#120]
Admin: 
![img_20170405_140408](https://cloud.githubusercontent.com/assets/8982139/24705806/2caa2644-1a16-11e7-90e1-1f2f27986ad2.jpg)

Frontend:
![img_20170405_135633](https://cloud.githubusercontent.com/assets/8982139/24705807/2cb6da9c-1a16-11e7-878e-59c6a100cfa2.jpg)

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [ ] when saving the updates of deactivate model answer of ordering question we get this error

![graphicgapupdate](https://user-images.githubusercontent.com/12035045/27769813-a2929ba0-5f32-11e7-8fc9-083f64c6b1e7.png)
