### ISSUE TITLE
TE-121: Association Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#121]
![img_20170406_131025](https://cloud.githubusercontent.com/assets/8982139/24860983/5654f084-1df7-11e7-9bae-d66f08434d18.jpg)

**Comment by babanesma** [comment]
Change the abbreviation to something appropriate

**Comment by AbdElmoneimMohamed** [comment]
@babanesma 
the pulll request is done
http://git.camelcasetech.com/camelCase/testing-engine/pulls/7

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [ ] when saving the updates of deactivate model answer of Assocation question we get this error

![graphicgapupdate](https://user-images.githubusercontent.com/12035045/27769813-a2929ba0-5f32-11e7-8fc9-083f64c6b1e7.png)

**Comment by solimansamy** [comment]
The issue had been solved
