### ISSUE TITLE
TE-122 : Demo ( 05 Apr ) issues 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#122]
- [x] 1- Voucher Number must be Number of vouchers. ( Consolidation File - Issue no.9 )
- [x] 2- We have to unify the Deactivate icon ( Consolidation File - Issue no.10 )
- [x] 3- not attempted answers are not shown in exam/answers ( Consolidation File - Issue no.8 )
- [x] 4- export test problem 
- [x] 5- attach test/questions/multimedia ( approved formats : formats )
- [x] 6- Create/edit testing center ( Consolidation File - Issue no.1 )
- [x] 7- Exam topics total percentage ( Consolidation File - Issue no.2 )
- [x] 8- Create Category  ( Consolidation File - Issue no.4 )
- [x] 9- Create/edit Test provider  ( Consolidation File - Issue no.5 )
- [x] 10-Topics in Question ( Consolidation File - Issue no.6 )

[Test Engine Consolidation File - Vol 3.docx](https://github.com/camelcasetechsd/testing-engine/files/909893/Test.Engine.Consolidation.File.-.Vol.3.docx)

**Comment by AbdElmoneimMohamed** [comment]
## QA Test
@badr4php 
- [x] when editing testing center the the days it has been selected in Weekly Schedule are not changed
- [x] there is error when creating new testingCenter
![testingcentererror](https://user-images.githubusercontent.com/12035045/28521677-081579d6-7075-11e7-810a-fa98e22daebe.png)

**Comment by badr4php** [comment]
1-fix editing TestingCenter problem - the days it has been selected in Weekly Schedule are not changed
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/103

2- this problem related to directory permissions ,it was fixed by Eng : adham
