### ISSUE TITLE
TE-123: Matching Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#123]
![img_20170406_130648](https://cloud.githubusercontent.com/assets/8982139/24861145/e5f8271a-1df7-11e7-9489-fe37fcb7f65d.jpg)

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [ ] when saving the updates of deactivate model answer of matching question we get this error

![graphicgapupdate](https://user-images.githubusercontent.com/12035045/27769813-a2929ba0-5f32-11e7-8fc9-083f64c6b1e7.png)

**Comment by solimansamy** [comment]
The issue had been solved
