### ISSUE TITLE
TE-125: Slider Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#125]
![img_20170406_132340](https://cloud.githubusercontent.com/assets/8982139/24861443/0b764020-1df9-11e7-96b6-491939666164.jpg)

**Comment by babanesma** [comment]
- I can delete one of the answers and then add another 3 answers 
- desktop version is missing

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [ ] when click on edit link of deactivate model-answers we get this error
![editslider](https://user-images.githubusercontent.com/12035045/27771326-f526bed6-5f4c-11e7-97ce-0dccf42d076b.png)

**Comment by solimansamy** [comment]
Issue had been solved
