### ISSUE TITLE
TE-126 : Import Users

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#126]
### Task Brief

> Create a form to import a csv file containing users to the system and select a test in a specific test center to create appointments for these users  
> The output will be a sheet ( available for download in csv format ) , containing the users and their appointments details ( date , time and workstation ) 

### Task in Details 
- A new form available for super admin , TEM ( Testing Engine Manager ) & TCA ( Testing Center Administrator )
- The form will contain the following fields : 
  - drop down for test providers
  - drop down for tests based on selected provider
  - drop down for testing centers based on selected tests ( TCA will only see Testing Centers assigned to him )
  - date selector to select the date of appointments 
  - file input field for the csv file 
- The file will be uploaded and processed 
  - The file will contain a row for each user
  - Each row will contain a user first name , last name and his email 
  - If the email is already registered in the system , then the registered user will be used otherwise a new user will be created .
  - Random password will be assigned for new users 
  - Other mandatory fields will be assigned to default values 
- After the file has been uploaded , the system should calculate the available slots based on the selected testing center , the duration of the selected test and the selected date 
- Then the system should schedule appointment for the users 
- If the number of users is bigger than the available slots in the selected date , then the system should turn to the next date immediately and so on until it schedules appointments for all the users imported 
- Then a sheet containing the users login details , appointment details should be available for the admin user confirm all the appointments at once or cancel them all.
- If he hits cancel all operation will be cancelled 
- If he hits confirm , the users and their appointments will be created .

### Technical Notes
- route : `/admin/users/import`
- Controller : `modules/admin/Users/Http/Controllers/ImportController.php`
- Model : `modules/admin/Users/Models/ImportUsers.php`
- Try to divide your code into classes , for example : 
  - user import into separate class
  - slots calculation into separate class 
  - appointment scheduling into separate class

**Comment by babanesma** [comment]
Pull Request : http://git.camelcasetech.com/camelCase/testing-engine/pulls/10

**Comment by ahmedelbougha** [comment]
- Importing user should be available to TCA and they can select their test center which they can import the test appointments into.

- Please remove the space at end of message line "Results are expired please import again "
http://git.camelcasetech.com/camelCase/testing-engine/pulls/10/files#diff-8d721a77ad1b1599e52fc7fce094085ce26d48fR103

- If no need, please remove the commented lines:
http://git.camelcasetech.com/camelCase/testing-engine/pulls/10/files#diff-8d721a77ad1b1599e52fc7fce094085ce26d48fR180

- It's better to have the caching key with ids of the entities instead of their names, I suggest:
          [$importRecord->id,
           $importRecord->import_date,
           $importRecord->test->id,
           $importRecord->testingCenter->id,
           $importRecord->import_file, ]
http://git.camelcasetech.com/camelCase/testing-engine/pulls/10/files#diff-8d721a77ad1b1599e52fc7fce094085ce26d48fR199

**Comment by babanesma** [comment]
@ahmedelbougha comments resolved

**Comment by badr4php** [comment]
when upload invalid csv file its return syntax error.
![importuser](https://user-images.githubusercontent.com/24792169/29125160-4e1751fe-7d1b-11e7-85eb-6b1a822541e7.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/126
