### ISSUE TITLE
TE-13: Create job queue and activation email process to the job queue ( TE-2 )

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#13]
related to #2

**Comment by babanesma** [comment]
Job queue has been added now , please check https://github.com/camelcasetechsd/testing-engine/wiki/Commands to run the queue:worker

**Comment by ahmedelbougha** [comment]
QA Issues:
- The job is failing with following error:
`[2017-03-21 12:34:30] development.ERROR: exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Builder::$email' in /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:381
Stack trace:
#0 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(381): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/var/www/vhosts...', 381, Array)
#1 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(312): Illuminate\Mail\Mailable->setAddress(Object(Illuminate\Database\Eloquent\Builder), NULL, 'from')
#2 /var/www/vhosts/testing-engine.camelcasetech.com/modules/admin/Users/Http/Mail/User.php(39): Illuminate\Mail\Mailable->from(Object(Illuminate\Database\Eloquent\Builder))
#3 [internal function]: App\Admin\Users\Http\Mail\User->build()
#4 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#5 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(109): Illuminate\Container\Container->call(Array)
#6 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(192): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer))
#7 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Mail/MailableMailer.php(99): Illuminate\Mail\Mailer->send(Object(App\Admin\Users\Http\Mail\User))
#8 /var/www/vhosts/testing-engine.camelcasetech.com/app/Jobs/SendActivationEmail.php(36): Illuminate\Mail\MailableMailer->send(Object(App\Admin\Users\Http\Mail\User))
#9 [internal function]: App\Jobs\SendActivationEmail->handle()
#10 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#11 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#12 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendActivationEmail))
#13 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendActivationEmail))
#14 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendActivationEmail), NULL)
#16 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#17 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#18 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(154): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#19 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#20 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#21 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#22 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#23 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#24 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#25 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/vhosts/testing-engine.camelcasetech.com/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 {main}`
