### ISSUE TITLE
TE-130 : Select Point Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#130]

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [x] when saving the updates of deactivate model answer of select point question we get this error

![selectpoint](https://user-images.githubusercontent.com/12035045/27770913-79f8696c-5f47-11e7-9056-1fed8f21f814.png)

**Comment by AbdElmoneimMohamed** [comment]
## QA issues

- [ ] there is error when create question of type select Point
![selectpoint](https://user-images.githubusercontent.com/12035045/28524884-9e5d0d2a-7082-11e7-8695-dcde11781356.png)
- [ ] when saving the updates of deactivate model answer of select point question we get this error
![selectpointerror](https://user-images.githubusercontent.com/12035045/28524895-a264a4f0-7082-11e7-8bbc-0ef6e204caa2.png)
