### ISSUE TITLE
TE-131 : Graphic Gap Questions ( TE-119 )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#131]
![img_20170413_182638](https://cloud.githubusercontent.com/assets/8982139/25086874/67c3be44-236b-11e7-9ef2-5c286ba828a6.jpg)

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [ ] when saving the updates of deactivate model answer of Graphic gap question we get this error.
`[EXCEPTION] Call to a member function populate() of non`

**Comment by solimansamy** [comment]
Screenshot https://camelcase.slack.com/files/soliman.samy/F6QACSCKH/27769813-a2929ba0-5f32-11e7-8fc9-083f64c6b1e7.png

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
it has been Solved

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Is it working on UAT server ?

**Comment by solimansamy** [comment]
I can't deactivate any model answer

**Comment by solimansamy** [comment]
related to #216
