### ISSUE TITLE
TE-132 : Graphic Associate Questions

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#132]

**Comment by badr4php** [comment]
pull request :  
https://git.camelcasetech.com/camelCase/testing-engine/pulls/15

**Comment by AbdElmoneimMohamed** [comment]
- [ ] when click on edit link of deacivate model answer of  Graphic Associate Questions we get this error

![associatedeactivate](https://user-images.githubusercontent.com/12035045/27769872-18037eee-5f34-11e7-8998-5eda26d5ca2c.png)

**Comment by solimansamy** [comment]
The issue had been solved
