### ISSUE TITLE
TE-140: Desktop Issues (TE-139)

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#140]
## Desktop 
- [x] Desktop app is showing js error when hitting next and previous
- [x] associate is not appearing on desktop
- [x] No picture appears in desktop app ( **table 16** )
- [x] When test taker try to start submitted exam, no need for proctor sign in. test taker here need message to remind him that this exam has been finished or expired. ( **table 20** )
- [x] Avoid duplicating uploaded files into 2 places while creating model answers ( modules/admin/Tests/Models/ModelAnswers.php::uploadMultimediaFile ) , but make the desktop app grabs the photos of the exam when it starts

## Notes for QA and review 
- Desktop Application should run exams smoothly without any js errors 
- Test Taker should sign in , view the exams not submitted before and could start them 
- Test Taker should be redirected to proctor login on type exam only 
- Images of Questions of all types and their model answers should be seen , and should be gotten from API not copied ( already implemented ) 
- Full Screen / Kiosk mode should only happen when exam start ( after proctor login in type exam ) 
- Full Screen / Kiosk Mode should be deactivated after finishing the exam

**Comment by badr4php** [comment]
pull request : https://git.camelcasetech.com/camelCase/testing-engine/pulls/65

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
- [ ] When test taker try to start submitted exam he  redirected to grading page but We only
need message to remind him that this exam has been finished or expired.

**Comment by badr4php** [comment]
There is conflict not resolved in tf.html file
![true-false](https://user-images.githubusercontent.com/24792169/28115699-3fa971ea-6706-11e7-950b-f2c518ab6e3a.png)

**Comment by badr4php** [comment]
Test Taker should be redirected to exam after proctor login , but now  he redirected to home.

**Comment by badr4php** [comment]
- [x] when click start exam on desk top its redirect to proctor login in all cases(test type  exam or test type practice ) 

- [ ] Full Screen / Kiosk mode happen when click start exam before proctor login (proctor login form displayed in Full Screen)

**Comment by badr4php** [comment]
Full Screen / Kiosk mode  happen when click start exam before proctor login (proctor login form displayed in  Full Screen)

**Comment by solimansamy** [comment]
When building the app I got this error after press login

**Comment by solimansamy** [comment]
Desktop app has already been build. When I try to login, I got this error

https://www.dropbox.com/s/0cpmg8qbd7fqmkx/Screenshot%20from%202017-08-01%2015%3A05%3A10.png?dl=0
