### ISSUE TITLE
TE-150 : Search In Email Templates(TE-147)

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#150]

**Comment by badr4php** [comment]
It's working

**Comment by solimansamy** [comment]
The issue exists on production
![screenshot from 2017-06-20 06-34-15](https://user-images.githubusercontent.com/9415375/27329138-852393b2-5582-11e7-9497-a8a6ace346d9.png)

**Comment by solimansamy** [comment]
I have checked the logs

development.ERROR: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1055 'testing_engine.emails.name' isn't in GROUP BY' in /var/www/vhosts/testing-engine.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77 Stack trace: #0 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('select count(*)...', Array) #1 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Doctrine\DBAL\Driver\PDOConnection->prepare('select count(*)...') #2 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(763): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array) #3 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure)) #4 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(351): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure)) #5 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1648): Illuminate\Database\Connection->select('select count(*)...', Array, true) #6 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1634): Illuminate\Database\Query\Builder->runSelect() #7 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1709): Illuminate\Database\Query\Builder->get() #8 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(500): Illuminate\Database\Query\Builder->getCountForPagination() #9 /var/www/vhosts/testing-engine.camelcasetech.com/modules/admin/Backend/Http/Controllers/EmailsController.php(76): Illuminate\Database\Eloquent\Builder->paginate(10) #10 [internal function]: App\Admin\Backend\Http\Controllers\EmailsController->search(Object(App\Admin\Backend\Http\Requests\EmailsRequest))

**Comment by badr4php** [comment]
pull request   https://git.camelcasetech.com/camelCase/testing-engine/pulls/80

**Comment by solimansamy** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/101
