### ISSUE TITLE
TE-151 : Spelling Check (TE-147)

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#151]
In appointment, recheck and correct the word Avalabile to Available in the green button.

**Comment by badr4php** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/75

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [x] fix the spelling of avalabile keyword
![sp](https://user-images.githubusercontent.com/12035045/27380267-c3879bf6-567e-11e7-9706-83acd53d9918.png)
