### ISSUE TITLE
TE-152 :  Deactivate Icon (TE-147)

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#152]
Deactivate Icon is not change in all pages of the site. http://thetalenttier.net/admin/tests/2/questions/113/model-answers

**Comment by badr4php** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/76

**Comment by solimansamy** [comment]
@badr4php I have left a comment here https://git.camelcasetech.com/camelCase/testing-engine/pulls/76#issuecomment-88

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Make sure activate/deactivate icons are working on all model answers

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy   activate/deactivate icons are working on model-answers list of all type of questions

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
please check the deactivate icon in http://local-testing-engine.com/admin/backend/reports
![deactivateicon](https://user-images.githubusercontent.com/12035045/27381246-682cea00-5682-11e7-86b3-d0d6a962944c.png)
