### ISSUE TITLE
TE-154: Exam Result: The result appears in the below report is not logic (TE-148)

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#154]
When the test taker finish the exam The result appears in the below report is not logic  .
![sssssss](https://user-images.githubusercontent.com/12035045/27285738-f43bf814-54fd-11e7-91ac-acf367d5578a.png)

**Comment by AbdElmoneimMohamed** [comment]
i created a exam and i found that this bug is resolved

this is screenShot when the test taker is Pass the exam 
![passexam](https://user-images.githubusercontent.com/12035045/27285815-31a67bde-54fe-11e7-909f-f3c2917f6540.png)

and this when is Fail
![screenshot from 2017-06-19 14 32 12](https://user-images.githubusercontent.com/12035045/27285833-4361b816-54fe-11e7-9345-2b078ca0954e.png)

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed  Can we make sure it's working also on production ?

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy  yes i think that because i also check his Tests and i found the same result
![softskilstest](https://user-images.githubusercontent.com/12035045/27287876-55bc67de-5505-11e7-953e-235270c4f5a7.png)

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy  when i check this bug i found that there is an error display when start exam for first time 
i think this error is appare when the System make shuffle for the Questions.

- [x] in /lib/Exams/Formation/Weight.php 
in shuffleQuestions method we call getTestQuestions method in getTestQuestions method we get the id from questionType 'TYPE_EXTENDED_ANSWER"
but if the test don't has  question of this type it make  an error 
so we must check first the question of this type not equal null before getting id from it

- [x] the same thing in /lib/Exams/Formation/BluePrint.php

![shufflequestions](https://user-images.githubusercontent.com/12035045/27287739-f6e625ce-5504-11e7-8d55-a1b74b2c93cc.png)

**Comment by ahmedelbougha** [comment]
A separate issue has been created and added to Backlog #161

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
this video is related to this issue 
[issue37.zip](https://github.com/camelcasetechsd/testing-engine/files/1099633/issue37.zip)
