### ISSUE TITLE
TE-155: Exam Reschedule (TE-147)

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#155]
If reschedule charge or cancellation charge is “0”,then there is no payment.

**Comment by badr4php** [comment]
pull request  https://git.camelcasetech.com/camelCase/testing-engine/pulls/79

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Make the of the following

- [x] Payment is working fine if reschedule has fees > 0 or fees = 0.

- [x] Payment is working fine if cancellation has fees > 0 or fees = 0.

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
- [x] Payment is not working fine if reschedule fees = 0.
this is the steps to fetch this bug
1 - create new test with Reschedule fees = 0
2 - schedule this test and remember the appointment
3- rescudule this test in another appointment 
and then go to reschedule page you will get the first option of appointment list
but in database it's store correctly

**Comment by badr4php** [comment]
I check it ,it's work fine.

**Comment by AbdElmoneimMohamed** [comment]
thank you @badr4php 
i checked it again and it's working fine
