### ISSUE TITLE
TE-156: There are some questions are opened in exam with their answers (TE-148)

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#156]
![image](https://user-images.githubusercontent.com/12035045/27331486-f1435470-55bd-11e7-8368-f78b96beada7.png)

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
i recheck this issue i found that this issue is Resolved
but
when i recheck this issue i found 2 bugs related to this issue

- [x] an image doesn't appare  when create new model Answers 
![modelanswererror](https://user-images.githubusercontent.com/12035045/27331906-ddfb747c-55bf-11e7-9b8a-2a5c514f9e65.png)

- [x] when creating new question the question type list not correct 
the extented answer question type don't display 
and display "Testing Question Types" and this is not type
![questiontypeerror](https://user-images.githubusercontent.com/12035045/27331984-4a5fd860-55c0-11e7-8226-d72b43521a7a.png)

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Is it working on production ?

**Comment by AbdElmoneimMohamed** [comment]
Yes it working

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Regarding bug#2 The extented answer question type don't display because it was deactivated, @badr4php said.

**Comment by badr4php** [comment]
pull request :   https://git.camelcasetech.com/camelCase/testing-engine/pulls/81

**Comment by badr4php** [comment]
I think Clint add this question type "Testing Question Types" before we prevent adding question type feature,So I think we need to remove it from  production database  .

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy
this video is related to this issue
[issue41.zip](https://github.com/camelcasetechsd/testing-engine/files/1099638/issue41.zip)
