### ISSUE TITLE
TE-157: some questions evaluated as wrong while they are correct  (TE-148)

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#157]
Some questions need to be adjusted with its model answers. They are evaluated as wrong while they are correct

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
there is a problem in Correction of questions
i create Test and answered all question Right put the Result was incorrect 
![correction](https://user-images.githubusercontent.com/12035045/27336239-36ae61e2-55cf-11e7-8968-c21a79b4da1a.png)

**Comment by ahmedelbougha** [comment]
After checking the different types of questions (15 types), here's the result:

	1-Multiple choice single: correct
	2-Multiple choice multiple: correct
	3-True/False: correct
	4-Drag/Drop: correct - problem with summary display
	5-Short Answer: correct
	6-Extended Answer
	7-Ordring: correct - problem with summary display
	8-Association: wrong
	9-Slider: correct 
	10-Hot Text: correct ( problem with displaying the model answers in frontend )
	11-Matching: wrong 
	12-HotSpot: correct - problem with summary display
	13-Graphic Gap: correct - problem with summary display
	14-Graphic Associate: correct - problem with summary display
	15-Select Point: correct - problem with summary display

**Comment by ahmedelbougha** [comment]
Ready for review:
http://git.camelcasetech.com/camelCase/testing-engine/pulls/84

**Comment by solimansamy** [comment]
:+1:

**Comment by AbdElmoneimMohamed** [comment]
@ahmedelbougha 

 ## True and False question bug #173
 ## Shuffling questions bug #174
