### ISSUE TITLE
TE-160: Weight Formation Exam Issue 

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#160]
It seems the calculation of number of questions in exam is wrong in case of Weight Formation.
Replication scenario: 

1. Create test of _weight formation_, and make total number of questions as 4.

2. Create 6 questions as bank of questions each with 25 weight

3. When taking exam, a user get only 1 question in his/her exam.

**Comment by solimansamy** [comment]
Related to #197 and #198
