### ISSUE TITLE
TE-167: Fixing the implementation of Hot Text

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#167]
Hot Text question type implementation is not correct:
Examples:

- [x] The below creation text, shows one extra option at end of the answer in frontend
```
this is a <answer><answer correct = 'true'>  correct answer</answer></answer> , then <answer> wrong</answer>, then <answer> wrong</answer>, then <answer> wrong</answer>
```
![screenshot from 2017-06-21 17-02-20](https://user-images.githubusercontent.com/8982139/27391172-7eb7e98e-56a3-11e7-913b-09e29452a6e3.png)

- [x] The below creation text doesn't show the correct answer
```
this is a <answer correct = 'true'>  correct answer</answer> , then <answer> wrong</answer>, then <answer> wrong</answer>, then <answer> wrong</answer>
```
![screenshot from 2017-06-21 17-02-05](https://user-images.githubusercontent.com/8982139/27391180-8793d86a-56a3-11e7-94fc-64f23441067c.png)

**Comment by badr4php** [comment]
pull request : https://git.camelcasetech.com/camelCase/testing-engine/pulls/87

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
the second point is not solved
please check it again in frontend

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
the second point is work fine now
but
- [ ] When we try to edit the  correct model answer  in backend the body of model answer doesn't appare
![editcorrectanswer](https://user-images.githubusercontent.com/12035045/27993973-cf95ce3e-64b3-11e7-9edb-9d361fc2b053.png)
