### ISSUE TITLE
TE-168: Cancellation appointment Error (TE-164)

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#168]
this error is display when we want to cancel an appointment in production
http://testing-engine.camelcasetech.com/test/cancelAppointmentPayment
![cancelation](https://user-images.githubusercontent.com/12035045/27391369-1ea5b94e-56a4-11e7-98ef-b8dedc38baa4.png)

**Comment by solimansamy** [comment]
@badr4php Here is the exception
development.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'payment_type' doesn't have a default value' in /var/www/vhosts/testing-engine.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL) #1 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(480): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(763): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `tr...', Array) #3 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `tr...', Array, Object(Closure)) #4 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `tr...', Array, Object(Closure)) #5 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `tr...', Array) #6 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `tr...', Array) #7 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `tr...', Array, 'id') #8 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #9 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1609): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #10 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1609): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #11 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1574): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #12 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1471): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #13 /var/www/vhosts/testing-engine.camelcasetech.com/app/Models/ModelAbstract.php(251): Illuminate\Database\Eloquent\Model->save() #14 /var/www/vhosts/testing-engine.camelcasetech.com/modules/frontend/Tests/Models/Payment.php(67): App\Models\ModelAbstract->save(Array) #15 /var/www/vhosts/testing-engine.camelcasetech.com/modules/frontend/Tests/Http/Controllers/PaymentController.php(94): App\Frontend\Tests\Models\Payment::cancel(Array) #16 [internal function]: App\Frontend\Tests\Http\Controllers\PaymentController->payForCancelAppointment(Object(Illuminate\Http\Request)) #17 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array) #18 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('payForCancelApp...', Array) #19 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Frontend\Tests\Http\Controllers\PaymentController), 'payForCancelApp...') #20 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController() #21 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #22 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #23 /var/www/vhosts/testing-engine.camelcasetech.com/modules/frontend/Base/Http/Middleware/FrontendTheme.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #24 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Frontend\Base\Http\Middleware\FrontendTheme->handle(Object(Illuminate\Http\Request), Object(Closure)) #25 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #26 /var/www/vhosts/testing-engine.camelcasetech.com/app/Http/Middleware/Acl.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #27 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\Acl->handle(Object(Illuminate\Http\Request), Object(Closure)) #28 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #29 /var/www/vhosts/testing-engine.camelcasetech.com/app/Http/Middleware/Localization.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #30 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure)) #31 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #32 /var/www/vhosts/testing-engine.camelcasetech.com/app/Http/Middleware/LogAfterRequest.php(15): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #33 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\LogAfterRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #34 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #35 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #36 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #37 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #38 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #39 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) #40 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #41 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #42 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #43 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #44 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #45 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #46 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #47 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #48 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #49 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #50 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #51 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #52 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #53 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #54 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #55 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #56 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #57 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #58 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #59 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #60 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #61 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #62 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #63 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #64 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #65 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #66 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #67 /var/www/vhosts/testing-engine.camelcasetech.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #68 /var/www/vhosts/testing-engine.camelcasetech.com/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

**Comment by badr4php** [comment]
this  was solved but not merged to master
it's solved in issue https://github.com/camelcasetechsd/testing-engine/issues/155
you can check code in develop  - https://git.camelcasetech.com/camelCase/testing-engine/src/bugs/TE_155_Exam_Reschedule/modules/frontend/Tests/Http/Controllers/PaymentController.php
