### ISSUE TITLE
TE-174: Shuffling questions bug (TE-157)

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#174]
## Criteria of Test availability
Test is available if:
1. If count of available questions **is greater than or equal** the questions total of a test

Test is not available if:
1. It has no questions.

## Criteria of Question availability
A question is available if:
1. Question type is extended answer.
2. It has a model answer (Except type is extended answer).
3. At least one model answer has right answer if question must have right answer (Except type is extended answer).

Except point 2 and 3, question **is NOT** available

 this error display when the model answer doesn't have right Answer
![rightanswers](https://user-images.githubusercontent.com/12035045/27633101-28775c8e-5bfe-11e7-9ef1-1519d3383524.png)

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
this is the pull request for this issue
http://git.camelcasetech.com/camelCase/testing-engine/pulls/90

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Please check my comments regarding the code

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
## QA Scenarios
- test is not available if :
 - [x] test has no questions
 - [x] test has questions but all questions don't have any model answers
 - [ ] test has questions with model answers and all questions have no model answer with right answer
   if the question must has right answer
 - [x] available question is less than test's questions total 

- question is not available (this mean is will not be in Exam questions)
 - [x] question have no model answers (except extended answer question type).
 - [x] if the question must have model answer with right answer but it not have (except extended answer question type).
