### ISSUE TITLE
TE-179 : Running Desktop Application

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#179]
Application is unknown to windows. It may need authentication certificate.
Windows 8 and 10 

**Updates**
- [electron-builder](https://github.com/electron-userland/electron-builder/) is used to facilitate the building mechanism , and will also helps to fix the code signing problem
- Pull Request : http://git.camelcasetech.com/camelCase/testing-engine/pulls/93

**Resources**
- https://github.com/electron-userland/electron-builder/wiki/Code-Signing#windows
- https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate
- https://mkaz.tech/geek/code-signing-a-windows-application/

**Comment by babanesma** [comment]
For this message not to appear , Application should be signed using `EV Code Signing Certificate`
A certificate should be bought from a vendor like this https://www.digicert.com/order/order-1.php ( currently worth $449 )

Please check the resources in the description 

I am copying @zhibek to confirm if there are no other solutions .

**Comment by zhibek** [comment]
@babanesma I'm not familiar with Windows Application authentication/certificates. However, I think we should check the following URLs to see if we can do this instead of needing an `EV Code Signing Certificate`:
https://msdn.microsoft.com/en-us/library/windows/desktop/mt637086(v=vs.85).aspx
https://developer.microsoft.com/en-us/windows/develop/app-certification-kit
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/certify-a-new-app

**Comment by solimansamy** [comment]
When trying to login
```
testing-engine/desktop/express-app/routes/auth.js:21
                if (response.statusCode == 200) {
                            ^

TypeError: Cannot read property 'statusCode' of undefined
    at /home/soliman/Projects/testing-engine/desktop/express-app/routes/auth.js:21:29
    at Request._callback (/home/soliman/Projects/testing-engine/desktop/express-app/lib/api.js:53:9)
    at self.callback (/home/soliman/Projects/testing-engine/desktop/express-app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/soliman/Projects/testing-engine/desktop/express-app/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
```
