### ISSUE TITLE
TE-187 : Translation file

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#187]
[translation-files.zip](https://github.com/camelcasetechsd/testing-engine/files/1170401/translation-files.zip)

**Comment by badr4php** [comment]
-attributes file
[attributes.csv.zip](https://github.com/camelcasetechsd/testing-engine/files/1185752/attributes.csv.zip)

**Comment by badr4php** [comment]
Missing data
[translation-files.csv.zip](https://github.com/camelcasetechsd/testing-engine/files/1191260/translation-files.csv.zip)

**Comment by solimansamy** [comment]
http://git.camelcasetech.com/camelCase/testing-engine/pulls/110

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/118

**Comment by solimansamy** [comment]
@badr4php 

- [x] We need to group all exception messages in a CSV.
- [x] We need to translate `AR` in English version to be `العربية`.
- [x] We need also to translate `title` for button and <a> tag.

**Comment by badr4php** [comment]
exceptions : 
[exceptions.csv.zip](https://github.com/camelcasetechsd/testing-engine/files/1203211/exceptions.csv.zip)
[attributes.csv.zip](https://github.com/camelcasetechsd/testing-engine/files/1203212/attributes.csv.zip)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/122

**Comment by badr4php** [comment]
- [ ]Yellow circle  found in wrong position in Arabic version for questions(Graphic Associate ,Graphic Gap,HotSpot,Select Point) .
![graphic-associate](https://user-images.githubusercontent.com/24792169/29026720-80561870-7b7d-11e7-9b89-54a2676cf1b9.png)
![graphic-gap](https://user-images.githubusercontent.com/24792169/29026721-806f736a-7b7d-11e7-9c23-657913d2769b.png)
