### ISSUE TITLE
TE-192 : Behat Test

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#192]
- [x] Login using all roles like admin, proctor, etc
- [x] Register
- [x] Create test with validation
- [x] Create question with validaton
- [x] Create model answer with validation
- [x] Ability to appointment an exam
- [x] Start Exam
- [x] Exam correction

**Comment by solimansamy** [comment]
http://git.camelcasetech.com/camelCase/testing-engine/pulls/113

**Comment by solimansamy** [comment]
Some missing scenarios
- [ ] Scenario for exam failure `ZERO` result.
- [ ] scenario for test availability.
- [ ] Delete all data has been inserted into DB using Behat scenarios.
