### ISSUE TITLE
TE-197 : Blueprint Formation bug

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#197]
- [ ] We have a bug in a method which calculate the Exam questions for Blueprint Test

the method  = ceil((topicPercentage * testTotalQuestions) / 100))
if the testTotalQuestions = 25 and 
the percentage of topicA = 30
the percentage of topicB = 25
the percentage of topicC = 15
the percentage of topicD = 20
the percentage of topicE = 10

then we have 
30 * 25 / 100 = 7.5   => 8  questions with topicA
25 * 25 / 100 = 6.25 => 7 questions with topicB
15 * 25 / 100 = 3.75 => 4 questions with topicC
20 * 25 / 100 = 5.0   => 5 questions with topicD
10 * 25 / 100 = 2.5   => 3 questions with topicE

then the total questions = 27  not equal the test questions = 25

**Comment by badr4php** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/134

**Comment by AbdElmoneimMohamed** [comment]
- [ ] the BluePrint Formula not working correctly with this scenario
i created test with total questions = 10
and created 5 topics
topic1 => 10 %
topic2 => 15 %
topic3 => 20 %
topic4 => 25 %
topic5 => 30 %

and created 10 questions for this test 
4 questions with topic5
3 questions with topic4
4 questions with topic3

but when started the exam i found that the total exam questions = 8 not 10 
![totalquestions](https://user-images.githubusercontent.com/12035045/29494058-db3d40fe-85a2-11e7-9ddc-0cbf91a35628.png)
