### ISSUE TITLE
TE-198 : Weight Formation Bug

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#198]
- [ ] We have a bug in a method which calculate the Exam questions for Weight Test

the method  = ceil((totalQuestionsWithSpecificWeight * testTotalQuestions) / 100))

if the testTotalQuestions = 5 and 

the total questions with weight 30 = 10
the total questions with weight 20 = 20
the total questions with weight 50 = 30

then we have 

10 * 5 / 100 = 0.5   => 1  question with weight 30
20 * 5 / 100 = 1.0   => 1 question with weight 20
30 * 5 / 100 = 1.5   => 2 questions with weight 50

then the total questions = 4  not equal the test questions = 5

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/133
