### ISSUE TITLE
TE-200: [BUG] Error Graphic Associate In Desktop App

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#200]
- [ ] user can't match two point together

**Comment by badr4php** [comment]
run this command to build desktop app
1- npm install
2- npm start

PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/130

**Comment by solimansamy** [comment]
@mohamedmahmoud After merging develop, the problem still exists

https://camelcase.slack.com/files/U5VC46Z6F/F73F964RL/screenshot_from_2017-09-13_19_17_59.png
