### ISSUE TITLE
TE-201 : [EXCEPTION] Trying to get property of non-object' when import a question For Blueprint test without topics

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#201]
- [ ] If test has Blueprint formation ,imported question must contain topics instead of weight .

**Comment by solimansamy** [comment]
https://camelcase.slack.com/files/soliman.samy/F6LS92NN6/-.txt

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/138

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Please check this change and be sure of the following:

1. Import is working fine in all cases.
2. Exception above has gone away.
