### ISSUE TITLE
TE-204: [ENHANCEMENT] Missing Translation data

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#204]
Some words in the following locations that need to be translated:
رسالة التأكيد من الموقع
التقارير
القارير الثابتة
الامتحانات
مواعيد الاختبارات
انشاء شهادة
التنزيلات
القسائم
الصفحة الرئيسية
رسائل الخطأ
بدء الامتحان

**Comment by badr4php** [comment]
[missing-data.csv.zip](https://github.com/camelcasetechsd/testing-engine/files/1242626/missing-data.csv.zip)

**Comment by badr4php** [comment]
[fixed-report.csv.zip](https://github.com/camelcasetechsd/testing-engine/files/1245206/fixed-report.csv.zip)

**Comment by badr4php** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/154

**Comment by AbdElmoneimMohamed** [comment]
### Home Page

- [ ] Admin Link

![admin](https://user-images.githubusercontent.com/12035045/29830547-df28d34e-8ce2-11e7-993c-c09ae7cbc044.png)

### Admin Page

![last5](https://user-images.githubusercontent.com/12035045/29830665-30b0a6ec-8ce3-11e7-903f-10cd544fdd43.png)
![edit5](https://user-images.githubusercontent.com/12035045/29830670-321286b8-8ce3-11e7-8066-6852977546d3.png)

### User Profile

- [ ] Personal Info, Login Info, Contact Info,

![profile](https://user-images.githubusercontent.com/12035045/29830874-b2b4b67e-8ce3-11e7-8959-6d07b51a275f.png)

### Import User

- [ ] import user
![importuser](https://user-images.githubusercontent.com/12035045/29830963-fcbdac94-8ce3-11e7-8b1f-3682b9289d31.png)

### Role Privilages

![selectallpre](https://user-images.githubusercontent.com/12035045/29831015-27966f28-8ce4-11e7-86a7-7db8e3ed4cbd.png)

### Testing Center
![testingcenter1](https://user-images.githubusercontent.com/12035045/29831124-723a5058-8ce4-11e7-970d-e274c5a17af2.png)


![testingcenter2](https://user-images.githubusercontent.com/12035045/29831181-9e43065e-8ce4-11e7-8520-d17b4ec4e776.png)

- [x] select provider Option
![testingcenter3](https://user-images.githubusercontent.com/12035045/29831235-c0156c86-8ce4-11e7-809e-b2cd453a557f.png)

![testingcenter4](https://user-images.githubusercontent.com/12035045/29831304-f39cf6dc-8ce4-11e7-84f1-6a6d8978131e.png)

### Workstaions
- [x] workstaions and labs Links
![workstaions](https://user-images.githubusercontent.com/12035045/29831368-349fade6-8ce5-11e7-98f4-9d0d5ea7c2ef.png)

![workstaion2](https://user-images.githubusercontent.com/12035045/29831391-51430baa-8ce5-11e7-9cde-df112f7b44a4.png)

![workstaion3](https://user-images.githubusercontent.com/12035045/29831423-68c238e6-8ce5-11e7-875b-2393c84edbce.png)

### Reports
- [ ] Edit Report, add constrains , remove constrain, And/Or 
![report](https://user-images.githubusercontent.com/12035045/29831577-dcc3b076-8ce5-11e7-9a92-59d09f9a6241.png)

### Settings

![settings](https://user-images.githubusercontent.com/12035045/29831681-2f56bbe4-8ce6-11e7-9dd7-353d204b8d17.png)

### Emails

![emails](https://user-images.githubusercontent.com/12035045/29831787-7da7ed4a-8ce6-11e7-83f8-f0f975a8a0ac.png)

### Tests

![test1](https://user-images.githubusercontent.com/12035045/29831862-c49aef72-8ce6-11e7-880e-c6eaf5a6c8d8.png)

![test2](https://user-images.githubusercontent.com/12035045/29831917-e9ed9b94-8ce6-11e7-836a-aba25c23258c.png)

### Questions

![question1](https://user-images.githubusercontent.com/12035045/29832065-489aa3ee-8ce7-11e7-96a0-0c54b540a089.png)

![question2](https://user-images.githubusercontent.com/12035045/29832069-49a6be4e-8ce7-11e7-9d73-8a3ef54b41f6.png)

![question3](https://user-images.githubusercontent.com/12035045/29832071-4bdb9bc6-8ce7-11e7-9626-e702de3acf12.png)

### Model Answers
- [ ]Association 1
![modelassociate](https://user-images.githubusercontent.com/12035045/29832201-bc1555e4-8ce7-11e7-8c50-a189f2b91dcb.png)
- [ ] Association 2
![modelasso2](https://user-images.githubusercontent.com/12035045/29832202-bebd2f24-8ce7-11e7-99f3-c05b74e56b43.png)
- [ ] slider
![slider1](https://user-images.githubusercontent.com/12035045/29832214-c481602e-8ce7-11e7-9aab-c25b426d3580.png)
- [ ] hot text Correct / answer button
![hot](https://user-images.githubusercontent.com/12035045/29832268-ef9f41d6-8ce7-11e7-8057-972dc7710659.png)
- [ ] all
![hotspot](https://user-images.githubusercontent.com/12035045/29832358-33d7a12c-8ce8-11e7-8d9b-648c58f8a62b.png)
- [ ] hotspot
![hotspot2](https://user-images.githubusercontent.com/12035045/29832438-8b91deb4-8ce8-11e7-8595-d7b9ec30d629.png)
![gg1](https://user-images.githubusercontent.com/12035045/29832513-bf9af7ae-8ce8-11e7-83ce-4e81a7cb35df.png)

### Providers

![providers](https://user-images.githubusercontent.com/12035045/29832815-b7a5aea8-8ce9-11e7-8225-87ad33d6a188.png)


### Test Appointment 

![testappoinment](https://user-images.githubusercontent.com/12035045/29832863-e44554b8-8ce9-11e7-86ce-dbf09de69133.png)

### Vouchers
![vouchertitle](https://user-images.githubusercontent.com/12035045/29832898-0080b708-8cea-11e7-8810-de32aedc3e2c.png)

**Comment by badr4php** [comment]
1-ip was translated to IP by client
2- I have problem with topic validation message its key was generated by client so I can't translate it.

**Comment by AbdElmoneimMohamed** [comment]
### Import Questions

- [ ] Import Question, Please Upload the question csv file in the following format

![importquestion](https://user-images.githubusercontent.com/12035045/29865319-88fcb4d4-8d75-11e7-9522-2cb322474621.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/160
