### ISSUE TITLE
TE-208: [ENHANCEMENT] Update question and model answer availability regarding multimedia to avoid images not shown in Exam

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#208]
- [x] If a question requires multimedia but it doesn't have a multimedia, question shouldn't be put in an exam
- [x] If a model answer requires multimedia but it doesn't have a multimedia, question shouldn't be put in an exam

**Comment by solimansamy** [comment]
After this fix we will avoid exception occurs when a test taker answers a question with no multimedia

https://camelcase.slack.com/files/soliman.samy/F6P6A7FJP/-.txt

https://camelcase.slack.com/files/soliman.samy/F6PAA8EDA/-.txt

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
http://git.camelcasetech.com/camelCase/testing-engine/pulls/137
