### ISSUE TITLE
TE-209: [EXCEPTION] 'Trying to get property of non-object' when correcting extended answer question

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#209]
https://camelcase.slack.com/files/soliman.samy/F6P7BCZU0/-.txt

**Comment by solimansamy** [comment]
Check the scenario below with steps

1. A test taker start an exam which have an extended answer question Q1.
2. Admin deactivates the question Q1.
3. Admin tries to correct the extended answer Q1.
4. Exception occurs.

**Comment by solimansamy** [comment]
This happens with testId=36. questionId= 328, examId=130

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/140
