### ISSUE TITLE
TE-213: [ENHANCEMENT] Disable topics when choosing weight formation in test form

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#213]
Also remove validation on it

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
https://git.camelcasetech.com/camelCase/testing-engine/pulls/143

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/145

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/166
