### ISSUE TITLE
TE-214: [BUG] Certificate is not related to the provider when creating tests

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#214]
![screenshot from 2017-08-20 11 39 45](https://user-images.githubusercontent.com/9415375/29493734-719206f4-859c-11e7-9e75-4af71eaac3a9.png)

**Comment by solimansamy** [comment]
While creating or editing some test, and when I chose a provider, the list of certificates must be only the chosen provider certificates. But now, all certificates is available for any provider.

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
https://git.camelcasetech.com/camelCase/testing-engine/pulls/144
