### ISSUE TITLE
TE-215: [BUG] Duplicated available workstations

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#215]
![screenshot from 2017-08-20 12 17 00](https://user-images.githubusercontent.com/9415375/29493994-94517580-85a1-11e7-9621-620e47ff3dd9.png)

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
this issue is not exist in local
and When checked it in UAT
i found that the testing Center in this bug ( id = 1) have two workstation with the same code 
![dublicated](https://user-images.githubusercontent.com/12035045/29495086-e4915d92-85b7-11e7-8a22-88e7c1da612b.png)

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy  
the problem in creating two workstation with the same code because of click on save button more than time fast when submitting the form data and this problem in all the system not Here only

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed Can we prevemt this ?

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/146
