### ISSUE TITLE
TE-217: [BUG] Deactivate Function Bugs

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#217]
- [x] when create new lab in Deactivate Testing Center
   1. create new Testing Center
   2. Deactivate it
   3. create new lab in this Testing Center
- [x] when assign new Test to Deactivate Testing Center
   1. create new Testing Center
   2. Deactivate it
   3. add new test for this Testing Center
- [x] when preview Deactivate Certificate there is JS Error
   1. create new Certificate
   2. Deactivate it
   3. edit it and try to preview it

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/148

**Comment by solimansamy** [comment]
- [x] When trying to deactivate a test which assigned to deactivated testing center.
