### ISSUE TITLE
TE-219: [BUG] ] Display 10 tests per page while working in Appointment

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#219]
![screenshot from 2017-08-22 15 06 35](https://user-images.githubusercontent.com/9415375/29566859-96702ce8-874b-11e7-9bda-2a034d1ec8a1.png)

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/149
