### ISSUE TITLE
TE-222: [ENHANCEMENT] In ordering type exclude the correct order when doing shuffling

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#222]
![screenshot from 2017-08-23 10 55 29](https://user-images.githubusercontent.com/9415375/29607548-d7afd5fe-87f1-11e7-90ef-4856ffeca510.png)

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/151

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/167
