### ISSUE TITLE
TE-223: [ENHANCEMENT] Hide start exam button, if test taker started exam before

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#223]

**Comment by badr4php** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/150

**Comment by solimansamy** [comment]
We need to apply this change on desktop app

**Comment by badr4php** [comment]
PR to apply this change in descktop
 https://git.camelcasetech.com/camelCase/testing-engine/pulls/177

**Comment by solimansamy** [comment]
Related to #245
