### ISSUE TITLE
TE-225: [BUG] Get questions which are shuffled into exam even if they are  deactivated, using withTrashed

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#225]
Check the below scenario:

1. A test taker starts an exam `A` with 10 questions.
2. Admin deactivates one of test questions and accidentally it was in the exam `A`. Let's say it's number 10.
3. When a test taker press `Next`, the deactivated question disappeared.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/156

**Comment by solimansamy** [comment]
@badr4php We have a problem here, If a test taker starts an exam and suddenly browser has been crashed or closed. At this moment he doesn't submit the exam, and also in_progress flag will be true all the time. What we need to do is a cron job that loops on all unfinished exams has been started and checks if the exam time has gone away or not. If yes, change exam status and raise in_progress to false

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed We need to get questions which are shuffled even if they are deactivated

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/165
