### ISSUE TITLE
TE-226 : [ENHANCEMENT] Update test availability regarding testing center and test formation

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#226]
1. Test is available if it assigns to testing center.
2. Test is available when its formation is `Weight` and all questions have weight > 0.
3. Test is available when its formation is `Blue Print` and all questions assign to certain topic.
4. If Question must has multimedia and this multimedia not exist ,this question will be not available.
5.If model answer must has multimedia and this multimedia not exist ,the question will not be available.

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/152
