### ISSUE TITLE
TE-227: [ENHANCEMENT] Save session into DB instead of storing into files

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#227]
**Client Complain**
When click on schedule, appointment is scheduled, but system logout. I tried this by myself and when I finished the schedule process the session has been terminated with no appeared reason, but you have keep it in your consideration that this error hasn’t been appeared in each schedule I don’t know why??!!

**Comment by solimansamy** [comment]
https://laravel.com/docs/5.4/session

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/155
