### ISSUE TITLE
TE-228: [BUG] Correct value in Slider question should be between Minimum and Maximum

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#228]
![screenshot from 2017-08-24 14 56 41](https://user-images.githubusercontent.com/9415375/29667645-7578b102-88dd-11e7-9f1c-00f272ad3036.png)
![screenshot from 2017-08-24 15 01 37](https://user-images.githubusercontent.com/9415375/29667647-7596f20c-88dd-11e7-86bd-2f045a83586d.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/157
