### ISSUE TITLE
TE-240 : [BUG] Multimedia should link to the exact date which multimedia had been uploaded NOT the current date

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#240]

**Comment by solimansamy** [comment]
http://testing-engine.camelcasetech.com/admin/tests/33/questions/292/multimedia

http://testing-engine.camelcasetech.com/questions/295/multimedia

We already have multimedia for this question

**Comment by solimansamy** [comment]
I noticed after build had been succeeded, all multimedia point to the date build.

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/174
