### ISSUE TITLE
TE-245: [ENHANCEMENT] Timeout exam message error

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#245]
- [x] dispaly the timeout exam message error when the test taker press the start exam

**Comment by solimansamy** [comment]
@abdelmoneim.mohamed Don't forget Desktop App

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/179
