### ISSUE TITLE
TE-246: [EXCEPTION] Error When correct question in Desktop app if it doesn't have answer

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#246]

**Comment by solimansamy** [comment]
@badr4php We need to check all questions with no answers

Till now we have exceptions in 

Association Question
https://camelcase.slack.com/files/U5VC46Z6F/F72K59NKE/-.txt

MultipleChoice Question
https://camelcase.slack.com/files/U5VC46Z6F/F73FLCPEJ/-.txt

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/181
