### ISSUE TITLE
TE-248: [BUG] We need to save unanswered questions from Desktop app as NULL

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#248]
https://camelcase.slack.com/files/U5VC46Z6F/F74DH8AGL/screenshot_from_2017-09-17_17_07_25.png

https://camelcase.slack.com/files/U5VC46Z6F/F758JK9ML/screenshot_from_2017-09-17_17_07_34.png

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/184
