### ISSUE TITLE
TE-250: [BUG] After payment is done system should redirect to the same domain I came from

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#250]

**Comment by solimansamy** [comment]
Trying to pay for an exam using voucher or paypal using http://thetalenttier.net/ domain. After payment is done, the system will redirect you to testing-engine.camelcasetech.com domain

**Comment by AbdElmoneimMohamed** [comment]
https://git.camelcasetech.com/camelCase/testing-engine/pulls/183
