### ISSUE TITLE
[NEW FEATURE] Export fixed reports using server side

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#253]

**Comment by solimansamy** [comment]
We need to export all data instead of first page, please remove JS plugin we're using to export data.

**Technical Approach**
- Create a new action for each export button
i. exportXLS
ii. exportTXT
iii. exportCSV
- It should call the parent action with filter parameters FixedReportsController::run() and return pagination.
- Each action should have its own header

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/192
