### ISSUE TITLE
[NEW FEATURE] Test taker must to have National ID and profile photo

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#257]

**Comment by solimansamy** [comment]
**Business Requirements**
- In the profile of the user (not in registration), 4 new fields to be added to the profile which are user photo, [National ID (Saudis)], and  [Passport ID and Iqama ID (Non Saudis)]
- Users can register as normal even they didn’t fill those fields
- Users cannot reserve test appointment unless they have filled the 3 fields filled and saved into their profiles (National ID field, [Passport ID and Iqama ID fields])
- In case the user tries to reserve appointment a flash message tells him that s/he must fill the fields required in the profile

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/201
