### ISSUE TITLE
TE-258: Add new code for testing center certificate

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#258]
**Business Requirements**
- Certificate code (Test Center ID - Exam Code - Test Taker ID)
- Each certificate must have a unique code formed of the 3 database fields values above
- In the certificate design tool the admin can select the location of the unique code on certificate design

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/202
