### ISSUE TITLE
Allow embedding audio and video objects while creating questions

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#259]

**Comment by solimansamy** [comment]
**Business Requirements**

- In the question creation/editing form, there’s an upload field, which allows the admin to upload images that will be displayed in the frontend exam (web and desktop).
- We need that field to allow uploading media files (audio and video) and display them in the frontend (web and desktop).
- The audio and video are part of the question body.

**Comment by solimansamy** [comment]
Check screenshot https://camelcase.slack.com/files/U5VC46Z6F/F7WBNJ6CQ/screenshot_from_2017-11-08_18_28_48.png

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/203
