### ISSUE TITLE
TE-260: [NEW FEATURE] System has to record time taken per question

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#260]

**Comment by solimansamy** [comment]
**Technical Approach**

- Exam timer depends on server side verification (in web).
- Add duration field to question_answers entity.
- Question timer/duration depends on server side verification (in web).
- As long as the user in the page of the question the timer/duration field is counting.
- Once the user moved to another question the timer/duration stops.
- If the user returns back to the question page again the timer/duration counts again.
- In the desktop application the timer/duration of both question and exam depends on local storage.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/204

**Comment by ahmedelbougha** [comment]
@badr4php please check my comments.

**Comment by ahmedelbougha** [comment]
@badr4php please check my QA comments in the PR

**Comment by ahmedelbougha** [comment]
Passed QA and Review.
Merged
