### ISSUE TITLE
TE-261: [NEW FEATURE] Test Center IP should be authorized by admin in order test taker can start an exam

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#261]
**Technical Approach**
- Add IP address entity linked to test center entity as many to one (test_center_id foreign key in ip addresses table).
- Add IP address field in the test_center admin.
- Restrict access to start exam in the web application.
- Restrict access to start exam in the desktop application.
- Don’t forget access denied to this IP message.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/205

**Comment by ahmedelbougha** [comment]
Please check my comments

**Comment by ahmedelbougha** [comment]
please check QA comments in PR

**Comment by ahmedelbougha** [comment]
Passed QA and Review
