### ISSUE TITLE
TE-262: [NEW FEATURE] Display results and status of the exam in appointment details

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#262]
**Technical Approach**
- Show the exam grade (percent) in the appointment details.
- Show the exam result (passed, failed, waiting for correction) in the appointment details.
- In case the exam is not finished show N/A in both fields.
- In case of result is (waiting for correction) show N/A in grade field.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/206

**Comment by ahmedelbougha** [comment]
Please check QA comments in PR

**Comment by ahmedelbougha** [comment]
Passed QA and Review
