### ISSUE TITLE
TE-266 : Activity Logs Filter

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#266]
We need to have one page with filter
Page is saying `Activity Logs`
With filter for example
Entity Type
User email
Entity ID
Date from/to

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/211

**Comment by solimansamy** [comment]
@badr4php Activity log is not listening to database when creating entities

**Comment by solimansamy** [comment]
@badr4php Also can we add entity id to filter data by
