### ISSUE TITLE
Allow CK Editor for questions

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#267]

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/212

**Comment by solimansamy** [comment]
@badr4php CKEditor is working fine when editing a question, but isn't working on exam interface. Also apply changes on desktop application. We need also remove CKEditor tags from question content, see attached
![screenshot from 2017-12-28 14 04 53](https://user-images.githubusercontent.com/9415375/34410337-2ee2099c-ebd8-11e7-826d-53b58b1ed84e.png)

**Comment by solimansamy** [comment]
![screenshot from 2017-12-28 14 06 29](https://user-images.githubusercontent.com/9415375/34410355-5130733a-ebd8-11e7-81bf-8e70be4548f1.png)
