### ISSUE TITLE
TCP should be able to mark the test as "Irregularity"

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#268]
**Business Requirements**

1. TCP should have his own page lists which exams are running now.
2. TCP should have the ability to mark the exam as `Irregularity`.
3. TCP should write a report of what exactly happened.
3. In such cases, the system will show the result as `Failed` attaching the “Irregularity Report” in the score report.

**Comment by badr4php** [comment]
PR :  https://git.camelcasetech.com/camelCase/testing-engine/pulls/213
