### ISSUE TITLE
TCA should have access to a page that lists all the appointments

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#272]

**Comment by solimansamy** [comment]
The calendar should display appointments with status.

**Comment by solimansamy** [comment]
https://learninglaravel.net/how-to-create-an-event-calendar-in-laravel

https://hdtuto.com/article/laravel-full-calendar-tutorial-example-from-scratch **I supported this**

**Comment by solimansamy** [comment]
Check google calendar here

![calender](https://user-images.githubusercontent.com/9415375/35566739-197615aa-05cb-11e8-8707-5f08248e8140.jpg)

**Comment by solimansamy** [comment]
https://github.com/maddhatter/laravel-fullcalendar

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/226
