### ISSUE TITLE
General issues in Testing Engine

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/testing-engine#279]

**Comment by solimansamy** [comment]
- [x] Question module: There are missing features in the CK Editor. Like: Font, font size, picture browser, we need it like `SkillsBuilder`.
- [x] rename the following menu names in the “Backend”:
The “Report” to be “Custom Reports” 
The “Fixed Reports” to be “Reports”
- [x] Proctor cannot access the irregularity report.
- [x] Add filter and export features in irregularity report.
- [x] The system should record how much time the test taker spends on each question, even if he goes back and forward within the exam.
RE; We already done with this, we need just to display the this info. Where can we do this ?
RE: under the reports and it will be for the admin only 
- [x] TCA can view reports on each test, each workstation and each TCP, The report is already there under fixed reports it may need to include filters and some additional fields. Check http://testing-engine.camelcasetech.com/admin/backend/fixed-reports/14/run

- [x] When making any modifications to some test center, the system checks for the input IP, which is good. But if there is no change in the IP the system holds the saving process and send message with: The IP address has already been taken!!!

- [x] As a user, when start an exam, I can access the reservation page and fined the below page screenshot. The Reschedule & Cancel Schedule appear even the exam is running 

- [x] I do not have Nationality field. And if I change the “Birth Country” the National ID is not changed to “Resident ID”

- [ ] When modifying the profile and click on save, I got a message to check the field “I agree to license agreement!”. Then this step goes 	in a closed loop without saving.


- [x] The old certificates are not working. They give error message when trying to edit.

- [x] Adding test center admins contact to the appointment details page

**Comment by solimansamy** [comment]
- [ ] rename the following menu names in the “Backend”:
The “Report” to be “Custom Reports” 
The “Fixed Reports” to be “Reports”

**Comment by badr4php** [comment]
- [x] https://git.camelcasetech.com/camelCase/testing-engine/pulls/222

- [x] https://git.camelcasetech.com/camelCase/testing-engine/pulls/223

- [x] https://git.camelcasetech.com/camelCase/testing-engine/pulls/225

- [x] https://git.camelcasetech.com/camelCase/testing-engine/pulls/227
