### ISSUE TITLE
TE-280 : Update Testing Engine Configuration Phase 2

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#280]

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/221

**Comment by solimansamy** [comment]
@badr4php We need to add 2 things
1. `$role = RoleEntity::where("code", RoleEntity::ROLE_SUPER_ADMIN)->orwhere("code",
                RoleEntity::ROLE_TESTING_ENGINE_MANAGER)->first();`
Remove the second orwhere.
2. Remove the log activities of **the super admin we created on the fly** after logout.

**Comment by badr4php** [comment]
PR :  https://git.camelcasetech.com/camelCase/testing-engine/pulls/228
