### ISSUE TITLE
TE-283 : Create CMS Module

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#283]
- [x] create  Pages module

- [x] create Menus  module

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/234

**Comment by solimansamy** [comment]
We need to create a menu module for testing engine, the menu should have a menu as parent and menu item as child, we can create one entity for that. We need some kind of caching for the menu.

Also we need to create a cms for page.

**Acceptance Criteria**

1. Admin can create a menu.
2. Admin can create a menu item under a certain menu
3. Admin can create a page
4. Admin Dashboard should have its existing menu - don't change the behavior
5. Users can navigate with the menu on frontend
6. Users can see the pages created by admin with link associated to each one.

**Comment by solimansamy** [comment]
@badr4php Can you please use `Redis` to cache menus into it

Check documentation here https://laravel.com/docs/5.5/redis

**Comment by ahmedelbougha** [comment]
done and merged
