### ISSUE TITLE
TE-284 :Change the way we used to handle assets paths 

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#284]
use larave helper method assets to generate assets paths

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/237

**Comment by babanesma** [comment]
@badr4php 
- css resources should be added to `additional_styles` not `additional_scripts`
- general css and js resources like jquery and jqueryui should be added to the default template `app.blade.php` . If the blade template doesn't inherit from a default template like the reports print templates , create a new default template for them .

**Comment by babanesma** [comment]
approved :+1:
