### ISSUE TITLE
TE-285 : apply new theme 

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#285]
/*************************** home routes **************************/
'/home' => 'HomeController@index'
/*************************** cms routes ****************************/
 '/pages/ uri ' =>  'PagesController@show' 
 '/pages/ id /multimedia' =>  'PagesController@getPageMultimedia' 

/************************ user routes *********************************/
  'login' => 'LoginController@showLoginForm'
  '/register' => 'RegisterController@showRegistrationForm'
  '/users/profile' =>  'ProfileController@index' 
  '/users/profile/show' =>  'ProfileController@show' 
  '/users/profile/edit' =>  'ProfileController@edit'  
  '/users/certificate/image/ certificate ' =>  'ProfileController@showCertificates' 
  '/users/certificate' =>  'ProfileController@certificate' 
  
/****************************** test routes ******************************/

 '/tests' =>  'TestsController@index' 
 '/tests/appointments' =>  'TestsController@appointments' 
 '/tests/ id ' =>  'TestsController@show' 
 '/tests/ id /testCenter/ tcId /schedule' =>  'TestsController@schedule' 
 '/tests/ id /testCenter/ tcId /schedule/create' =>  'TestsController@create' 
 '/tests/ id /testCenter/ tcId /reschedule/ taId ' =>  'TestsController@edit' 
  

/***************************** appointments routes *************************/
     'appointments/ id ' =>  'AppointmentsController@show' 
     'appointments/ id /start-exam' =>  'AppointmentsController@startExam' 
     'appointments/ id /proctor-login' =>  'AppointmentsController@proctorLogin'

**Comment by ahmedelbougha** [comment]
@Ali-Galal @LamiaSalah 

We need the content of each page of the following:

- [x] 1- home page - currently implemented static, but needs dynamic content

- [x] 2-cms page

- [x] 3-login

- [x] 4-register

- [x] 5-profile details

- [x] 6-edit profile

- [x] 7- certificates listing

- [x] 8- certificate

- [x] 9- tests listing

- [x] 10-test details

- [x] 11-appointments listing

- [x] 12-test schedule

- [x] 13- test reschedule

- [x] 14-start exam

- [x] 15-proctor login

**Comment by Ali-Galal** [comment]
Home Page ==> Lamia
CMS ==> Lamia
Login Page ==> like the search but with the login component 
register ==> like the contact us but with the out the addresses and the map
profile details ==> same like edit profile ==> like the register
certificates listing ==> like the faculity profile http://tivatheme.com/html/university/faculity-profile.html

**Comment by ahmedelbougha** [comment]
When @Ali-Galal send them, Tuesday (20/03/2018)

**Comment by Ali-Galal** [comment]
certificate ==> like the faculty profile http://tivatheme.com/html/university/faculity-profile.html
tests listing ==> like the blog list http://tivatheme.com/html/university/blog-list.html
test details == > like the product detail http://tivatheme.com/html/university/product-detail.html
appointments listing==> like the faculty profile http://tivatheme.com/html/university/faculity-profile.html

test schedule  ==> as the static page 
test reschedule==> as the static page 
start exam==> as the static page 
proctor login==> as the login page

**Comment by Ali-Galal** [comment]
any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal 
This is the last template (CMS) as per @LamiaSalah 
http://tivatheme.com/html/university/course-detail.html

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal 
Everything should be ready by end next Tuesday (03/04/2018) En Shaa Allah, but we will push new designs of different templates one by one starting from Thursday (29/03/2018) En Shaa Allah.

**Comment by badr4php** [comment]
PR to Display Certificates As Slider IN Certificates Listing Page : https://git.camelcasetech.com/camelCase/testing-engine/pulls/252
PR to apply New Theme For Test Schedule And Test Reschedule Page : https://git.camelcasetech.com/camelCase/testing-engine/pulls/253

**Comment by mahmoud-hussien1** [comment]
PR for design cms and test details pages:
http://git.camelcasetech.com/camelCase/testing-engine/pulls/254
PR for design all login pages (need to be merged last):
http://git.camelcasetech.com/camelCase/testing-engine/pulls/255
PR for design profile detail and exam pages:
http://git.camelcasetech.com/camelCase/testing-engine/pulls/256
PR for design of layout and other pages(parent branch):
http://git.camelcasetech.com/camelCase/testing-engine/pulls/245
