### ISSUE TITLE
TTT - Integration Sample

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/testing-engine#287]
A sample for the response and the headers for each API (Sent by email) 
[TestingEngine-Doroob-Integration.docx](https://github.com/camelcasetechsd/testing-engine/files/1778524/TestingEngine-Doroob-Integration.docx)

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Should be ready by tomorrow morning 6/3/2018 En Shaa Allah

**Comment by Ali-Galal** [comment]
update me please

**Comment by ahmedelbougha** [comment]
API with sample responses:
[TestingEngine-Doroob-Integration_With_Sample_Responses.docx](https://github.com/camelcasetechsd/testing-engine/files/1785620/TestingEngine-Doroob-Integration_With_Sample_Responses.docx)

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please confirm and close the issue if all is fine.
