### ISSUE TITLE
TTT - pages links not being saved 

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/testing-engine#289]
pages link not being saved

**Comment by ahmedelbougha** [comment]
@Ali-Galal, @LamiaSalah 
As more description for this to confirm your requirements:
You need to add menu items under other menu items, is that correct? 
If not please provide the scenario about what you need to do.

**Comment by ahmedelbougha** [comment]
When you try to use forward slashes in path of the pages, it's not saved 
Tuesday (20/3/2018)

**Comment by Ali-Galal** [comment]
any update?

**Comment by ahmedelbougha** [comment]
Yes that has been pushed last Tuesday.
The ticket seems to be not updated sorry for that.
