### ISSUE TITLE
TTT - Preview/Copy options

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#291]
Wednesday (21/03/2018)

**Comment by ahmedelbougha** [comment]
done

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
Kindly confirm

**Comment by LamiaSalah** [comment]
@ahmedelbougha please clarify what this issue is

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
This feature allow admin make duplicate/copy of a page in the CMS.
