### ISSUE TITLE
Photos on Skilled Matrix 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#295]
Ahmed there's no browsing option in order to add a photo with the etext on Skilled Matrix

**Comment by LamiaSalah** [comment]
Dear Ahmed,

Could you please advise when this will be fixed? We need to have it asap

**Comment by ahmedelbougha** [comment]
This issue was fixed since long time ago, users already uploaded images to the CMS page.
No activities since 28th of March, confirm to close.

**Comment by LamiaSalah** [comment]
Confirmed
