### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#298]
**URL**: http://testing-engine.camelcasetech.com/admin/users/12/edit 
**Path** :  Admin> Users>   Users> Edit
**Description**: 
When editing the profile, user personal Info section > Birth City/Province field has no data to choose from. So, profile cannot be save.
![image](https://user-images.githubusercontent.com/11155105/38022336-e1a08f54-3287-11e8-89a8-22384c445f65.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
This issue has been fixed long time ago, please confirm

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
This is your first reply to me on that issue.

Done.
