### ISSUE TITLE
Create New Testing Centers

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#299]
**URL**: http://testing-engine.camelcasetech.com/admin/testing-centers/create
**Path**: Admin> Testing Centers> Create New Testing Centers
**Description**: 
New testing center cannot be created!!!!
Also the map is not working.
 
![image](https://user-images.githubusercontent.com/11155105/38023424-f5ac629a-328a-11e8-9042-36ff4b796e37.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Scenario please, also the map is blocked until you provide me with gemail details

**Comment by HeshamHassan** [comment]
Duplicated Issue
All needed data were sent to issue #317
