### ISSUE TITLE
Multimedia at Question List

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#302]
URL: http://testing-engine.camelcasetech.com/admin/tests/1/questions
Path: Admin> Tests> Tests> Show> Test Questions> Multimedia
Description: When click on “Download” in Multimedia filed, I got this error:
![image](https://user-images.githubusercontent.com/11155105/38023865-fe029f58-328b-11e8-88d0-7e865ad181ee.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
Now, I got "Server Error" when downloading the pictures from the questions list or from edit page of the question.

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check.

**Comment by HeshamHassan** [comment]
Done
