### ISSUE TITLE
Create New Certificates

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#304]
URL: http://testing-engine.camelcasetech.com/admin/tests/certificates/create
Path: Admin> Tests> Certificates> Create New Certificates
Description: Error…
![image](https://user-images.githubusercontent.com/11155105/38024055-8ee9c24e-328c-11e8-8477-8c0a8e920c90.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
Dear @HeshamHassan
You already opened another issue #323 that referring to certificate preview, which means you already tested this and found it working. :)
Please close this if you feel it's ok to go.

**Comment by HeshamHassan** [comment]
Ok
