### ISSUE TITLE
Vouchers Payment

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#306]
**URL:** http://testing-engine.camelcasetech.com/admin/tests/list-vouchers
**Path:** Admin> Vouchers
**Description:** There is no payment for the vouchers

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
We are in middle of discussion of new Vouchers and Payment system, this issue is not valid. You can confirm later with Ali, please confirm and close.

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly advice!
