### ISSUE TITLE
Missing Downloads

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#307]
**URL:** http://testing-engine.camelcasetech.com/admin/downloads
**Description:** There is no "Downloads Desktop App". The page is empty.

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
This is not a bug, this should contains the desktop app there when it's compiled on the server.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Kindly determined the expected time to take the desk top app. alive?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update??

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update??

> @ahmedelbougha
> Kindly determined the expected time to take the desktop app. alive?

**Comment by ahmedelbougha** [comment]
done, @HeshamHassan please confirm and close

**Comment by HeshamHassan** [comment]
App. is available, but not installable. #367

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Close this issue, and you have another issue for making the installer.
