### ISSUE TITLE
Question Multimedia: Pictures

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#308]
**URL:** http://testing-engine.camelcasetech.com/admin/tests/2/questions/114/edit
**Path:** Admin> Tests> Show> Test Questions> Edit
**Description:** The picture that attached to the question cannot be replaced or removed.
![image](https://user-images.githubusercontent.com/11155105/38081782-895e85be-334d-11e8-8e4e-37f9b86f49b5.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Would you please check

**Comment by HeshamHassan** [comment]
Done
