### ISSUE TITLE
Schedule Fees

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#309]
**URL:** http://testing-engine.camelcasetech.com/admin/tests/2/edit
**Path:** Admin> Tests> Edit
**Description:** Schedule Fee can be 0.0 (without fee)
![image](https://user-images.githubusercontent.com/11155105/38081850-b7b3422e-334d-11e8-9eae-2e9096ebaeea.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
@Ali-Galal 
Kindly advice

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
is this a bug??

**Comment by Ali-Galal** [comment]
@ahmedelbougha some exams could be free of charge

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Sorry, I cannot understand where is the problem, please elaborate more.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we need the schedule fee field to accept the "0" value.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
The normal tests doesn't support "0" as schedule fees, while practice exam does, so if you want a test that free of charge you can use practice tests.

**Comment by HeshamHassan** [comment]
We have some cases that require 0 fee

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is an enhancement please advise.

**Comment by Ali-Galal** [comment]
@ahmedelbougha Estimation?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly update!

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
1 hour or less.
Date: 20/09/2018

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, please confirm and close.

**Comment by HeshamHassan** [comment]
Done.
