### ISSUE TITLE
Start an Exam

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#310]
**URL:** http://testing-engine.camelcasetech.com/appointments/2
**Path:** User> Appointments> Exam list
**Description:** When click on an exam from the exam appointments list, I get the appointment details instead of exam starting.
![image](https://user-images.githubusercontent.com/11155105/38082028-29a998f6-334e-11e8-924f-5376f2c49825.png)

**Comment by HeshamHassan** [comment]
Kindly inform us when this issue will be delivered?

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please update the ticket with exact scenario and if it's still there.

**Comment by HeshamHassan** [comment]
1. I reserved an exam and the appointment expired and stopped.
2. Then I tried to reserve the same exam again, but the page of the exams list shows empty list. So I cannot reserve the same exam again.

**Comment by ahmedelbougha** [comment]
Thanks @HeshamHassan 
@mahmoud-hussien1 would you please check the above scenario?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
This is the same issue that appeared in issue #341
