### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/testing-engine#311]
@ahmedelbougha kindly inform me when we can get the technical documentation for the testing engine system

**Comment by Ali-Galal** [comment]
update me please

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please confirm and close?

**Comment by Ali-Galal** [comment]
@ahmedelbougha waiting you modifications as our phone conversation

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
ok will check this and reply ASAP nchallah
