### ISSUE TITLE
Admin Cannot Deactivate/Reactivate any user

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#315]
**URL** : http://www.skilledmatrix.com/admin/users/8/edit
**Path:** Admin> Users> User>   Edit Profile
**Subject:** The activation checkbox in   the users profile is not present for admin to deactivate or reactivate any user.
![image](https://user-images.githubusercontent.com/11155105/39751745-ccd21084-52c1-11e8-9cab-23b9d66a2692.png)

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
The user can be activated/deactivate from the listing page, this is an enhancement, please advise.

**Comment by Ali-Galal** [comment]
@ahmedelbougha ignore
