### ISSUE TITLE
Role Privileges Appearance

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#316]
**URL:** http://www.skilledmatrix.com/admin/users/roles/6/privileges
**Path:Admin>** Users> Roles>   Edit
**Subject:** The role privileges appear   like that:
![image](https://user-images.githubusercontent.com/11155105/39752449-27399c66-52c4-11e8-95d2-18bfc1fb2eb8.png)

- [ ] It has to be more organized like that:

![image](https://user-images.githubusercontent.com/11155105/39752453-2b57abee-52c4-11e8-9f6f-2f0f2dfa7073.png)

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is an enhancement, please advise

**Comment by Ali-Galal** [comment]
@ahmedelbougha No, it is not an enhancement, it should be organized

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/25/issue-316-role-privileges-appearance/diff

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
As agreed we did it the simplest way, please confirm to close.

**Comment by Ali-Galal** [comment]
@HeshamHassan Kindly confirm

**Comment by HeshamHassan** [comment]
Done
