### ISSUE TITLE
Map at Create New Testing Center Form

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#317]
**URL:** http://www.skilledmatrix.com/admin/testing-centers/create
**Path:** Admin> Testing   Center> Create New Testing Center
**Subject:** Map is not working. So, I cannot   create any new testing center.
![image](https://user-images.githubusercontent.com/11155105/39753408-5a5bf604-52c7-11e8-802b-0086f135cc35.png)

**Comment by mahmoud-hussien1** [comment]
estimated fixing date: 17/05/2018.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please send us the username/password of Gamil account we can use for this?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Any updates?

**Comment by Ali-Galal** [comment]
@ahmedelbougha 
Testingengine.engine@gmail.com           
TeTe@123456

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Not yet.

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Would you please check the details above and fix.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
This email/pass are not found, did you create this email?

**Comment by HeshamHassan** [comment]
@Ali-Galal 
Kindly advice.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
kindly use the following email:
testengine.engine@gmail.com

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
The new testing center form is still not working.

Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
I'll send you the page where you put payment card details to allow map display correctly En Shaa Allah.

**Comment by Ali-Galal** [comment]
@ahmedelbougha ok, send it. 

@HeshamHassan whenever you receive it share it with Mohammed Tarek

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update Please?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, confirm and close

**Comment by HeshamHassan** [comment]
Not yet...
![image](https://user-images.githubusercontent.com/11155105/48852305-1cf22300-edbe-11e8-8d94-c859b9f60b9d.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
List the scenario for to debug.

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Check the issue above and fix.

**Comment by HeshamHassan** [comment]
Just try to create a new testing center from the admin backend.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan working on this

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
- [x] New testing center has been created successfully.

But the map at the form shows the location of Boudhh - Kathmandu from Nepal!
![image](https://user-images.githubusercontent.com/11155105/50274350-1bb02680-044e-11e9-9aba-9f376ef1fe32.png)

- [x] Need the start point of the mab to be "Current Location" or "Riyadh City".

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
