### ISSUE TITLE
Country and Province Names

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#318]
**Subject:** In all registration forms…   update the province names.   you can use the names provided in this URL: https://www.bayt.com/en/jobseeker/my-account/ , the list is available in both languages: Ar. & En.

![image](https://user-images.githubusercontent.com/11155105/39754844-380cfeae-52cc-11e8-80e2-c2d10618f799.png)                 ![image](https://user-images.githubusercontent.com/11155105/39754910-7257631a-52cc-11e8-91fc-29d0e4603210.png)

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is enhancement, please advise.

**Comment by Ali-Galal** [comment]
@ahmedelbougha the implemented menu does not contain the official names (spilling) of the cities, however,  give me the table name in the database I will update it by myself,

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/23/add-namear-column-to-cities-table/diff

**Comment by Ali-Galal** [comment]
@ahmedelbougha any update?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is already merged and on production now, we took the countries and cities from B ayt, but the issue, that there's lot of countries are missing cities, my suggestion is to make user entry field in order to fill this.

**Comment by HeshamHassan** [comment]
Done

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I don't think this is done yet, as lot of countries are missing cities as I mentioned above.

**Comment by mahmoud-hussien1** [comment]
fixed

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
please, test.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
@mahmoud-hussien1  is working on this to include the latest changes.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Did "mahmoud-hussien1" finish working on this issue as mentioned above?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
> @HeshamHassan
> @mahmoud-hussien1 is working on this to include the latest changes.

**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
the registration form NOW has the city DDM empty. I cannot create any new user or edit resident user.
![image](https://user-images.githubusercontent.com/11155105/48052079-06da4500-e1b8-11e8-891f-dc38fbda1c90.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, confirm and close

**Comment by HeshamHassan** [comment]
Done
