### ISSUE TITLE
Print Report Design

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#320]
**URL:** http://www.skilledmatrix.com/admin/backend/reports/1/run
**Subject:** The output report has no formatted design.
![image](https://user-images.githubusercontent.com/11155105/39760036-eb489720-52dc-11e8-9845-4372594fdaac.png)

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please advise this is an enhancement.

**Comment by Ali-Galal** [comment]
@ahmedelbougha no, it is not. every report in any system should have print and export buttons

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
That wasn't part of the proposal, the 2 functions above (print and export) for each/any report are new features, please check again.

**Comment by Ali-Galal** [comment]
@ahmedelbougha when you mention report you have to add print and export buttons to it, as I said before  every report in any system have print and export buttons

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please include this in our call, as this is not my understanding.
Thank you.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly check the attached sample.

[Reports Suggested Design.xlsx](https://github.com/camelcasetechsd/testing-engine/files/2364081/Reports.Suggested.Design.xlsx)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @HeshamHassan 
We need to discuss the above, Ali let's have quick call tomorrow about this.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we already have the export feature, we need only to add a printable format to the export feature such as (PDF), however, just drop the time to set the call

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
- [x] Report hard copy is missing its title.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
