### ISSUE TITLE
Email Templates Editor

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#321]
**URL:** http://www.skilledmatrix.com/admin/backend/emails/1/edit
**Path:** Admin> Backend>   Emails> Edit
**Subject:** Email template field must   be CKEditor.
![image](https://user-images.githubusercontent.com/11155105/39762011-38294850-52e2-11e8-9a6d-bebd5a2e68ed.png)

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please advise, this enhancement, also it may lead to unexpected behaviors in emails since CKeditor is adding tags that may not needed.

**Comment by Ali-Galal** [comment]
@ahmedelbougha this is not an enhancement, and we talked about this before as we cannot expect any email template creator as a plain text this will be a nightmare to edit.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
As per our discussion after you put this comment, this is critical since it contains variables that may be affected with any kind of formatting, my recommendation not to do it with CKEditor.
Please confirm to close

**Comment by ahmedelbougha** [comment]
closed due to inactivity.
