### ISSUE TITLE
Activity Logs Terms

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#322]
**URL:** http://www.skilledmatrix.com/admin/backend/activity-log?page=60
**Path:** Admin> Backend>   Activity Logs
**Subject:** 
As per earlier conversation   about this issue with Soliman…   
- [ ] Any record value about changing   passwords must not appear in symbols and hushes. you can replace it with “Password   reset”, “Password Change”, “Old Password/New Password” or some other term that refers to this operation.
- [ ] the Key: “userhush” must be changed to Password

![image](https://user-images.githubusercontent.com/11155105/39762747-27d8386a-52e4-11e8-9939-c34a2220551f.png)

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is an enhancement.

**Comment by Ali-Galal** [comment]
@ahmedelbougha what is going on Ahmed, I kept receiving enhancement word in every issue we raised,

do you told me that I have to accept the rubbish in the screenshot

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/22/remove-userhash-from-acrivity-log-table/diff

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please confirm the rubbish in the screenshot was removed to close the ticket.

**Comment by ahmedelbougha** [comment]
closed due to inactivity.

**Comment by HeshamHassan** [comment]
Hushes still in the log file:

![image](https://user-images.githubusercontent.com/11155105/41820064-5ef18d3c-77d4-11e8-9b76-c28797091b23.png)

**Comment by ahmedelbougha** [comment]
Merged
@HeshamHassan 
Would you please retest this issue.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Password is ok in the log file
But there is a lot of hushes that I do not know what is it for?
You can check an example at log file page no. 137 you will find "Body" phrase under Key column I didn't get its meaning.
I appreciate if you have manual or documentation for this part explains the phrases used in it

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
That because we encrypt the body of some content, I'll make sure to make them uncrypted En Shaa Allah.

@mahmoud-hussien1 
Would you please check and fix

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by ahmedelbougha** [comment]
done 
@HeshamHassan check and confirm

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close

**Comment by HeshamHassan** [comment]
Done.
