### ISSUE TITLE
Certificate Preview

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#323]
**URL:** http://www.skilledmatrix.com/admin/tests/certificates/2/edit
**Path:** Admin> Tests>   Certificates> edit
**Subject:**
- [ ] Certificate preview is not working:
![image](https://user-images.githubusercontent.com/11155105/39808264-22655324-5387-11e8-908a-465436915f27.png)

**Comment by badr4php** [comment]
@ahmedelbougha  Please send log file

**Comment by mahmoud-hussien1** [comment]
estimated fixing date: 17/05/2018

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
What is the extension needs to be installed?

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
php_exif.dll

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I didn't install the above extension yet.

**Comment by ahmedelbougha** [comment]
the extension has been installed on the server, preview issue has been fixed.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please check and confirm.

**Comment by HeshamHassan** [comment]
Done.
