### ISSUE TITLE
Create New Appointment

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#324]
**URL:** http://skilledmatrix.com/tests/appointments
**Path:** Student> Appointment>   Appointment
**Subject:** The appointment page is not   working.
![image](https://user-images.githubusercontent.com/11155105/39868180-1df1d4f4-5461-11e8-8ad9-3bdf0501c155.png)

![image](https://user-images.githubusercontent.com/11155105/39868182-21b613a2-5461-11e8-98e3-99f82c823f19.png)

**Comment by badr4php** [comment]
@ahmedelbougha  Please send log file

**Comment by mahmoud-hussien1** [comment]
estimated fixing date: 17/05/2018

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please confirm to close?

**Comment by ahmedelbougha** [comment]
closed due to inactivity.

**Comment by HeshamHassan** [comment]
- [ ] The new appointment is now giving an empty list. 
![image](https://user-images.githubusercontent.com/11155105/41846196-9e5072e0-787e-11e8-95be-f97b8af7f691.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan we will check the issue, and let you know.
Important this is different issue of the ticket, so I'll create different ticket
