### ISSUE TITLE
Pages on CMS

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#325]
@ahmedelbougha Please advise where the pages that have been uploaded earlier twice on the CMS have gone.

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by Ali-Galal** [comment]
@ahmedelbougha this issue has the highest priority

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @LamiaSalah 
That was due to moving to new server, but we have the backup of database contains the pages you filled I will upload it by end of today En Shaa Allah.

**Comment by LamiaSalah** [comment]
@ahmedelbougha please confirm back when uploaded

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal 
I uploaded the backup database, and I checked the admin, I can see created CMS Pages there.
