### ISSUE TITLE
Logo at the header 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#328]
@ahmedelbougha please note that the logo needs to be displayed with the frame around it. Could you please amend it?

**Comment by ahmedelbougha** [comment]
Today

**Comment by ahmedelbougha** [comment]
@LamiaSalah
Home page and logo uploaded
Note the home page is experimental and not final yet, we need you final comments urgently to finish this as soon as possible

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal 
Please advise?

**Comment by ahmedelbougha** [comment]
I will close this ticket as @LamiaSalah already replied on #326 to avoid confusion.
