### ISSUE TITLE
Link Creation 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#329]
@ahmedelbougha on creating menu items, there are no options in the drop-down of the parent field.
Also not all the pages links appear in the drop-down of the path field.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
We will check the issue of parent, but what are the missing pages in drop-down? I can see 38 pages in the drop-down, while there are 40 pages created (2 are disabled). Please review that again and confirm if issue is present.

**Comment by LamiaSalah** [comment]
@ahmedelbougha there are no  pages that appear in the drop down of links

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please check the screenshot below, do you something different on your side?
![te](https://user-images.githubusercontent.com/8982139/41415259-75139518-6fe8-11e8-8153-2ae3a4f94cf0.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha thanks Ahmed. That's fine

**Comment by LamiaSalah** [comment]
@ahmedelbougha  I just rechecked this and the page tab is not there. The URL should appear automatically after selecting the page below. Please advise

**Comment by ahmedelbougha** [comment]
@LamiaSalah It works fine I tested it myself
![temenu](https://user-images.githubusercontent.com/8982139/41821390-1b245baa-77e0-11e8-8732-b545720e6c75.png)
, are you sure it's not working for you?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Parent menu item is working fine, please check and confirm.

**Comment by LamiaSalah** [comment]
@ahmedelbougha the parent drop down menu has nothing to show, it's not working

**Comment by LamiaSalah** [comment]
@ahmedelbougha no, it's not

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Per our phone call please confirm and close this ticket.

**Comment by LamiaSalah** [comment]
when I create a new menu item it should appear in the parent dropdown, this doesn't happen

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please check the screenshot, according to the setup, I have make this available up to 9th level.
![level9](https://user-images.githubusercontent.com/8982139/43523812-de497edc-959d-11e8-80f9-e8a94cda5c58.png)
