### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#330]
@ahmedelbougha there's only option of adding menus, no option of adding menu items, so I can't create the main menu

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
This is not like Skillsbuilder, where we have multiple menus, here we only have one menu, so any menu items are supposed to appear in the main menu of the website.

**Comment by LamiaSalah** [comment]
@ahmedelbougha I already created an item and it doesn't appear in the menu bar!

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please check it should be appearing now.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please confirm and close the issue

**Comment by LamiaSalah** [comment]
@ahmedelbougha confirmed
