### ISSUE TITLE
Tests don's appear in search page 

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#332]
- [ ] The new appointment is now giving an empty list. 
![image](https://user-images.githubusercontent.com/11155105/41846196-9e5072e0-787e-11e8-95be-f97b8af7f691.png)

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
The appointment process is not complete. It stops on "Available Workstation" step.
![image](https://user-images.githubusercontent.com/11155105/42573333-7fb4e5fc-8524-11e8-9229-32e4357584f5.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
done, @HeshamHassan please check and confirm.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
It works with Admin only.
I cannot run it from other test-takers.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Did you ever check the test taker role permissions?!

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I changed the permissions from admin and it works now for test takers, please check and confirm!!!

**Comment by HeshamHassan** [comment]
The same error, but this time when I tried to pay with a valid voucher.
![image](https://user-images.githubusercontent.com/11155105/43044890-47e276da-8db7-11e8-924b-0dd635c1fa3d.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
done please confirm

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
confirm and close please.

**Comment by HeshamHassan** [comment]
Done.
