### ISSUE TITLE
Custom Report Error

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#334]
**URL:** http://skilledmatrix.com/admin/backend/reports/12/edit
**Path:** Admin> Backend> Custom   Report
**Description:**
- [ ] When saving a custom   report that contains “ 0 “ value in the constrains, the system gives error   and report cannot be edited again.      
![image](https://user-images.githubusercontent.com/11155105/42025977-9e95995e-7ace-11e8-8350-6703bf85c835.png)

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/45/issue-334-change-empty-to-isset-in/diff

**Comment by ahmedelbougha** [comment]
done

**Comment by ahmedelbougha** [comment]
@HeshamHassan please check and confirm

**Comment by HeshamHassan** [comment]
Done
