### ISSUE TITLE
Custom Report – Join Type” Terms

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#336]
**URL:** http://skilledmatrix.com/admin/backend/reports/
**Path:** Admin> Backend> Custom Report
**Description:**
- [ ] Kindly explain the “Join Type” content terms? And how to you them?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
example category table and tests table. If category table (left table) has records with ids = 1, 2, 3, and 4 and you are trying to join tests table (right table) that has records with category_ids = 1, 2, 3 and 0:

"Inner Join" means you want to get all from left table (ids = 1, 2, 3) and related records from right table (category_id = 1,2,3), so it shouldn't display category with id = 4 and tests with category_id = 0.
 
"Left Join" means you want to get all from left table (ids = 1, 2, 3, 4) and related records from right table (category_id = 1,2,3), so it shouldn't display tests with category_id = 0.

"Right Join" means you want to get all from right table (category_ids = 1, 2, 3, 0) and related records from left table (id = 1,2,3), so it shouldn't display category with id = 4.
