### ISSUE TITLE
Custom Report Design Instruction Error

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#337]
**URL:** http://skilledmatrix.com/admin/backend/reports/17/edit
**Path:** Admin> Backend> Custom Report> Edit report H test 02
**Description:**
I created the following report:
![image](https://user-images.githubusercontent.com/11155105/42032921-cb94431e-7ae3-11e8-89b5-6de219e009b8.png)
The report results were ok in the first run. With the second run, the report results were not reasonable. The I edit that report again. I found the tables order changed as shown:
![image](https://user-images.githubusercontent.com/11155105/42032931-d4a57fa4-7ae3-11e8-94ef-38658a9d8dac.png)

- [ ] Keep the tables in its original order as it is created with no change when closing, saving or running the report.

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and fix.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
We have created a similar report to yours it's called `H test-02 CamelCase` and it worked fine.
1- http://skilledmatrix.com/admin/backend/reports/20/edit
2- http://skilledmatrix.com/admin/backend/reports/20/run
The edit page seems to be working fine.
One important note: according to the image attached above you are using the columns from same table to join ex: `users.id equals users.id` that is wrong it should be `users.id equals role_user.user_id` and so on.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
I cannot check. the table order in the report changes each time I change the checking factors.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/53/issue-337-enhancement-to-report-creater/diff

**Comment by HeshamHassan** [comment]
@ahmedelbougha
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan we added new field group to use it for ordering the table, check and confirm please.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
This issue has been fixed please confirm and close.
