### ISSUE TITLE
Encryption 

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/testing-engine#338]
@ahmedelbougha I need to encrypt the information in the database

**Comment by Ali-Galal** [comment]
@ahmedelbougha Kindly update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
will check and reply this next week nchallah

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by MuhammedMahdy** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly advice.
