### ISSUE TITLE
Answer Model - Body Textbox

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#340]
**Subject:**
The "Body" textbox that found at model answer page cannot carry long text (maximum 255 letter )
- [ ] open the limit of model answer "Body" text box.
![image](https://user-images.githubusercontent.com/11155105/42508527-89a80a04-8451-11e8-8da7-a7454867f841.png)

**Comment by HeshamHassan** [comment]
**Update:**
Also, the question body cannot accept more than 1000 character.
- [ ] open the limit of "Question Body" text box.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/48/extend-length-model-answer-body/diff

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Answer body: increased to 1000 characters
Question body: is 1000 characters

do you want more characters or is this fine?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Make them without limitation, **specially** Question Body

**Comment by ahmedelbougha** [comment]
Mahmoud please change type to text

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly, urgent update with delivery date.

**Comment by ahmedelbougha** [comment]
2 hours En Shaa Allah

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/51/issue-340-change-type-of-model-answer-to/diff

**Comment by ahmedelbougha** [comment]
done. @HeshamHassan please confirm

**Comment by HeshamHassan** [comment]
- [x] Model answer still maximum: 255 character 
- [x] Question body is working good.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
done please confirm

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
confirm and close

**Comment by HeshamHassan** [comment]
Done.
