### ISSUE TITLE
Create appointment

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#341]
@ahmedelbougha 
I cannot create an appointment with the user with "Test Taker Role".
The new appointment worked with Super Admin only.
Kindly Advice!!!

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
What is the scenario? Did you check the user permission in the backend?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 

_**Scenario:**_ 

1. Create User (KWP T.Taker) with role "Test Taker"
2. Create Test
3. Assigned the admin and proctor to Testing Center 1
4. Attached the test to Testing Center 1
5. Loged in as KWP t.taker 
6. Clicked on Appointment
7. Clicked on create new appointment
8. Nothing happen.
9. Tried new appointment with another T.Taker user and the same result.
10. Tried new appointment with S.Admin..... it works!!!

Did I forget something???

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
I have an assessment entered. I cannot check if is is working right or not.
We need it ASAP.
**Kindly help**

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
 ### Note
With Admin login.. I can start to create appointment till choosing the exam date. and when clicking on Available Work Station button, I get this page:
![image](https://user-images.githubusercontent.com/11155105/42748049-5ae32718-88e7-11e8-90ac-f969a7b2f453.png)

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/50/issue-341-create-appointment/diff

**Comment by ahmedelbougha** [comment]
done, @HeshamHassan please confirm.

**Comment by HeshamHassan** [comment]
Sorry @ahmedelbougha !
I cannot test this issue. there is no active user except Admin.
We need to solve issue #314 first.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Sorry, this issue is not depending on user type, if the admin is working fine, then most probably the other users are working fine too, or it will be just matter of permissions.
Please check using the admin for now and confirm if it's working.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
I tested this issue with admin user. It stopped after I input the voucher and pressed ok.
I got the same error "page not found"

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
I'm not sure what is the scenario you followed, but I just did another Test Scheduling using voucher right now, on this Test http://skilledmatrix.com/testav/3

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Till now... it's good
I created an appointment. 
![image](https://user-images.githubusercontent.com/11155105/43183271-33b224a2-8fed-11e8-99a3-bfa439f1fb71.png)

But, I need the last step in this process: 
- [ ] How to start the booked exam/assessment?

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
it appears in appointment show page (like: http://skilledmatrix.com/appointments/5) when it's available to start (in 30 minute after schedule time).

**Comment by HeshamHassan** [comment]
Exam is ready to start as shown in appointment show page (http://skilledmatrix.com/appointments/6).
- [ ] From where candidate can start it?
![image](https://user-images.githubusercontent.com/11155105/43244725-7649566a-90b4-11e8-8011-73f0c5cd3d1e.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
I still cannot start my exam from the online portal.

Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan, @Ali-Galal 
In order to book an appointment and display "Start Exam" button, please take care of the following:
1- The current used time zone is UTC.
2- The time slots that you are using are compared to time zone used by the application (UTC)
3- If the current time is between start time and 30 minutes after you can see the "Start Exam" button inside the appointment details page
4- That above is only applicable if you didn't start the exam before.

Example:
1- You scheduled an appointment by 19/09/2018 at Test Center 1  at 15:00.
2- You go to your appointments page then click "View Details" button in front of the appointment
3- You can find Start Exam button in details page

Check the screen shot below:

![skilledmatrixexam](https://user-images.githubusercontent.com/8982139/45763104-1c0f0a80-bc30-11e8-9594-6f89bdd62a18.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Grate, 
I will check that scenario and reply to you.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
please confirm and close

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
The ((Start Exam)) button is not present.
Scenario:
Login as Admin
I Created an appointment: Sunday 10:00 am
On Sunday 10:00 am I opened the appointment page.
I opened the exam: COMMUNICATION SKILLS ASSESSMENT
I did not find the **Start Exam** button

Check the screenshot date and URL:
![image](https://user-images.githubusercontent.com/11155105/46579502-f483b480-ca1b-11e8-8de5-f4beb2e1622c.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Also the same issue with the desktop app.
![image](https://user-images.githubusercontent.com/11155105/46579587-82ac6a80-ca1d-11e8-848b-f334c169bea1.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
The time zone on the system is unified on UTC (Coordinated Universal Time), so ALL the appointments are working with that unified time zone (not KSA time zone). So you have to compare your time with UTC while you are creating the appointment.
@Ali-Galal @HeshamHassan 
We have only one time zone in the application not multiple time zones, so if you need to set the time zone to KSA that's fine but you cannot use other time zones i.e. if someone from USA made schedule on 10:00 AM, then it's 10:00 AM in KSA not in USA.

Hope this answers your question

**Comment by Ali-Galal** [comment]
@ahmedelbougha the booking should follow the TC time zone

**Comment by ahmedelbougha** [comment]
Thanks Ali, but I couldn't find time zone by that name (TC), would you please elaborate?

**Comment by Ali-Galal** [comment]
@ahmedelbougha TC meaning Testing Center

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This leads to new feature, as the testing-engine doesn't support multiple timezone right now, it just supports one timezone.

**Comment by Ali-Galal** [comment]
@ahmedelbougha 
1- in mean time set it to follow Riyadh Time Zone
2- add the new to the proposal.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
Fixed, confirm and close.

**Comment by HeshamHassan** [comment]
Exam appointment was @ 10:30am
![image](https://user-images.githubusercontent.com/11155105/48889378-b82edb00-ee46-11e8-87d7-0cb60611e1ce.png)

- [ ] I cannot find the "Start Exam" button 
![image](https://user-images.githubusercontent.com/11155105/48889746-e4972700-ee47-11e8-868d-ac42e601b69a.png)

**Comment by HeshamHassan** [comment]
Any update?

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and confirm it's working.

**Comment by HeshamHassan** [comment]
Done.
