### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#342]
@ahmedelbougha Table frames need to be seen as discussed.

**Comment by Ali-Galal** [comment]
Example:
http://skilledmatrix.com/Certification-Partner-Programs/Authorised-Certification-Centres/Program-Options

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed

**Comment by HeshamHassan** [comment]
Done

**Comment by LamiaSalah** [comment]
@ahmedelbougha please enable the option of dragging the columns to be able to change sizes

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan
Please check with @LamiaSalah  and @Ali-Galal, as we communicate about this by email.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close.

**Comment by LamiaSalah** [comment]
Confirmed
