### ISSUE TITLE
icon on pages

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#345]
@ahmedelbougha Please note there's an icon at the top of each photo in all internal pages that appear in the front end. Please delete it

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
Fixed

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close

**Comment by LamiaSalah** [comment]
Confirmed
