### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#347]
[Footer.docx](https://github.com/camelcasetechsd/testing-engine/files/2253777/Footer.docx)

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise status

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
In progress, expected today

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
One thing in regard to *"Contact Us" Page*, cannot you do this using CMS? Why should we do it?

**Comment by LamiaSalah** [comment]
@ahmedelbougha I already created the page, I mean the internal layout. If I can do this, please let me know how.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by LamiaSalah** [comment]
Please update the footer with the attached layout
[Footer.docx](https://github.com/camelcasetechsd/testing-engine/files/2364113/Footer.docx)
 and content and fix its background

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Where is the new background?

**Comment by LamiaSalah** [comment]
@ahmedelbougha how does it look like? I can't see it in the original template

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
The current background of the footer in website is the original one in the template.

**Comment by LamiaSalah** [comment]
@ahmedelbougha should it be a photo or what?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
It was fixed, but we are waiting for the background image or color from your side.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
As you requested, we have removed the dimensions image and stick to gray background.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please confirm and close

**Comment by LamiaSalah** [comment]
The layout is OK, but please also make the first letter only in caps lock

**Comment by ahmedelbougha** [comment]
Where is that @LamiaSalah ?

**Comment by LamiaSalah** [comment]
@ahmedelbougha the text in the footer

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Done, please confirm and close.

**Comment by LamiaSalah** [comment]
@ahmedelbougha the titles are still in the same format.

**Comment by ahmedelbougha** [comment]
@LamiaSalah If you mean the title are being all caps, that is the design implementation, we made it in the way you want now, please confirm and close

**Comment by ahmedelbougha** [comment]
@MoatazAbdAlmageed 
1- 3 boxes height must be equal
2- z-index of 4 blue boxes

**Comment by MoatazAbdAlmageed** [comment]
@ahmedelbougha I finalized it please check.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please confirm and close.

**Comment by LamiaSalah** [comment]
@ahmedelbougha the format is fixed, but the content itself needs to be changed like the header, the same menu, order and titles.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by HeshamHassan** [comment]
- [ ] Update the footer to match the menu bar contents.
![image](https://user-images.githubusercontent.com/11155105/50273683-603ac280-044c-11e9-8e20-5ab3282faf02.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal @ahmedelbougha @LamiaSalah 
will include this as new feature please confirm ?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
I think it is fixing the footer.

**@Ali-Galal** 
Kindly advice.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc I'm not sure why this is a new feature?? It's just editing the content of the footer to match with the current header menu.

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc I'm not sure why this is a new feature?? It's just editing the content of the footer to match with the current header menu.

ok @LamiaSalah just please discuss this with @ahmedelbougha and let me know the final decision

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @HeshamHassan @ahmedelbougha 
footer updated please confirm and close

**Comment by HeshamHassan** [comment]
My issue point has Done.
@LamiaSalah : Pls check.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc Confirmed
