### ISSUE TITLE
Menu Items Weight

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#348]
@ahmedelbougha we need to have a menu weight to be able to set the items in order in the menu.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Issue has been fixed.

**Comment by LamiaSalah** [comment]
@ahmedelbougha it's not working

**Comment by ahmedelbougha** [comment]
@LamiaSalah as I show you on the phone yesterday, it's working please confirm and close the issue.

**Comment by LamiaSalah** [comment]
Confirmed
