### ISSUE TITLE
Edit User Profile

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#349]
**URL:** http://skilledmatrix.com/users/profile/edit
**Path:** User Menu> Profile>   Edit
**Subject:** 
User profile gives an error when click on save button after any modifying process
![image](https://user-images.githubusercontent.com/11155105/44627720-61932d00-a93b-11e8-800c-bebc5ca7e31f.png)

![image](https://user-images.githubusercontent.com/11155105/44627721-6526b400-a93b-11e8-8acd-b28e0f47ebb8.png)

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
i edit 
**### admin** 
- first name (non English): هشام
- last name (non English): حسن

**and it works.**

**### test taker**
- first name (non English): هشام
- last name (non English): حسن
- National ID: 1234567890
- Passport ID: 1234567890

**and also works.**

**Comment by HeshamHassan** [comment]
OK
It's working now.
