### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#350]
We need to have the option of linking text to a pdf doc.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan @LamiaSalah @Ali-Galal  
Please elaborate the issue.
