### ISSUE TITLE
Pending Issues 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#353]
- Please add the search bar at the top
- Please add Shopping Cart

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
It seems they are new requirements, I'm not sure if you have send me details about it?

**Comment by LamiaSalah** [comment]
@ahmedelbougha we just need to add a search bar and shopping cart option. How doable is this?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
It's doable, but it take time and effort, and I of course it needs clear requirements.

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal 
We need the requirements of this.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we just need to add a search bar and shopping cart option. 

what kind of requirements ?! please elaborate

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Currently, we don't have any products in the website, what will be added in the shopping cart? If we are talking about vouchers, then this is already part of new payment system requirements, so opening separate issue doesn't make sense.

For search bar, what is the functionality of that search bar? which content will it searches in? we have quite lot content there like pages, tests, providers, test centers ...etc. so what will the search bar do exactly?

**Comment by Ali-Galal** [comment]
@LamiaSalah @HeshamHassan @ahmedelbougha hold any issues related to the payment as we are going to change the workflow from A to Z.

@LamiaSalah please answer the part of the Search bar.

**Comment by LamiaSalah** [comment]
@ahmedelbougha @Ali-Galal this search bar will for searching different tests. If this is not in place now as no tests are added yet, we can postpone it for now.

**Comment by Ali-Galal** [comment]
@LamiaSalah so, it will search in test names, am I correct? if yes, kindly explain the output page

**Comment by LamiaSalah** [comment]
@Ali-Galal yes correct. It should direct to the relevant test page if this is what you mean

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal @HeshamHassan 
We added search field to tests listing page.
Fixed, confirm and close.

**Comment by HeshamHassan** [comment]
The search field is available now.
But what about the shopping cart?
@Ali-Galal and @LamiaSalah Kindly advice..

**Comment by Ali-Galal** [comment]
@LamiaSalah please check the search issue,confirm and close it. regarding the cart it will be ignored in mean time as I explained above.

**Comment by LamiaSalah** [comment]
@ahmedelbougha  please send me the link

**Comment by LamiaSalah** [comment]
@ahmedelbougha we need to have the search bar throughout the whole website like any other website as the attached. 
![image](https://user-images.githubusercontent.com/37042927/48980063-f0dfe600-f0cc-11e8-8e39-0c6ab7b287a3.png)

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
I can add it, but this doesn't make sense, the issue here is that we search bar is only related to Tests, if we add it to the other website pages, then it gives the impression that it's a search bar for the whole website not just for tests.

**Comment by LamiaSalah** [comment]
@ahmedelbougha Tests are a section of the website, so people can search for any info in general and not just tests.

**Comment by Ali-Galal** [comment]
@ahmedelbougha add it to the header, please

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal @ahmedelbougha @LamiaSalah 
will include `search bar at header for all website` as new feature please confirm ?

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly Advice.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mohamedMahdyCc** [comment]
> **@mohamedMahdyCc**
> Any update?

@HeshamHassan 
waiting for approve to start estimation for this feature

**Comment by Ali-Galal** [comment]
rejected
