### ISSUE TITLE
Payment when exam fees=0

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#355]
**@ahmedelbougha** 
After fixing issue #309 and the exam fee can be 0 "free of charge"
The appointment must not ask for any payment.

_Please urgent, so I can check issue #341_

**Comment by ahmedelbougha** [comment]
@Ali-Galal @HeshamHassan 
This is considered as feature completion issue of 309, I'll add the time to the time of 309.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This may take 1 day, please confirm to go ahead.

**Comment by MoatazAbdAlmageed** [comment]
@ahmedelbougha Done, Please check

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
Check and confirm

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Waiting for fixing issue #341

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Why do you link this to #341? you can schedule an appointment whether you started the exam or not, I cannot see why the 2 issues are linked?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please close this issue if it's done, no need to link it to another issue.

**Comment by Ali-Galal** [comment]
@ahmedelbougha this is still open because we still have a problem with the zero fees, because the appointment scheduling still asking for payment or paypal.

**Comment by ahmedelbougha** [comment]
@Ali-Galal, thanks will check and let you know En Shaa Allah.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please fix this ASAP.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha Done! will merge and push to server today nchallah

**Comment by HeshamHassan** [comment]
Done
