### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#358]
The login button is not working in all pages except Homepage.
![image](https://user-images.githubusercontent.com/11155105/46655881-6d6a4400-cbb5-11e8-9719-9b1531089257.png)

**Comment by MoatazAbdAlmageed** [comment]
@ahmedelbougha Fixed it commit => 65694271f86dfd21c0e437fe58412b0a8a625550

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please check and confirm.

**Comment by HeshamHassan** [comment]
Done.
