### ISSUE TITLE
Printing Exam Result and Certificate

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#359]
How can I print the exam result and its certificate?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update??????

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
You can use Ctrl+p, currently we don't have this feature in the application itself, and if you are mentioning the application can " The application should print out the results", that means on the screen not on paper.

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly Advice!!

**Comment by Ali-Galal** [comment]
@ahmedelbougha it could be a solution in the results, but it is not possible with the certificate

**Comment by HeshamHassan** [comment]
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
As I said before this is not available for certificate, if you want to add it as new feature, please let us know.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we need start exam to see the certificate print-out, kindly solve the issue number 341 to check

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal 
> @ahmedelbougha we need start exam to see the certificate print-out, kindly solve the issue number 341 to check

yes this issue 341 is done and closed, what next ?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
I will create a new certificate and attach it to an exam, then I will create an appointment to conduct that exam to check how to print the success certificate.

**Comment by HeshamHassan** [comment]
**@mahmoud-hussien1** 
I cannot attach the certificate to the test.
![image](https://user-images.githubusercontent.com/11155105/50443663-785f8580-0915-11e9-893d-10e5404adb74.png)

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan as the message appeared, this test was taken before. so you can't edit it.

**Comment by HeshamHassan** [comment]
I cannot edit. So:
- I cannot add or attache certificate to that exam. 
- If the exam has a certificate, I cannot change this certificate.

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan yes, if exam taken, you can't edit it or attach certificate to it.

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
please confirm and close if you seen it's done.

**Comment by HeshamHassan** [comment]
> I cannot edit. So:
> 
> * I cannot add or attache certificate to that exam.
> * If the exam has a certificate, I cannot change this certificate.

This issue transfared to a new issue #383
