### ISSUE TITLE
Reports' Definition

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#360]
The below table contains the SkilledMatrix reports' definition. 
Kindly confirm or modify.

ID | Report Title | Definition
-- | -- | --
1 | My Dashboard | Activities summary shown in tables, charts, and graphs.
2 | Exam Skillset Detail | Shows exam and skillset data for candidates.
4 | Inventory | Status and count of inventory for the selected organization
5 | Inventory By Station | Inventory allocated to each station
6 | Inventory Transactions | Inventory transaction details
7 | Multi-site Active Children | Multisite's active Testing Centers name, city, country,   phone, and e-mail address.
8 | Multi-site Inventory | Status and inventory count for branch
9 | Multi-site Results | Exam results for each branch of a Parent Customer for a   specific exam date
10 | Multi-site Results Date Range | Exam results for a branch of a Parent Customer for a date range of up to one year ago.
11 | Order Detail | Details of a specific order
12 | Orders | Orders summary information
13 | Results | Exam results with Candidate and exam details.
14 | Results Plus | Exam results for a test center with more information than the   Results report.
15 | Results by Exam Group | Exam results for selected Exam Groups of the Test Center. Exam results taken at other Test Centers for the Exam Groups are also retrieved.
16 | Results by Exam Group Plus | Blend of Results by Exam Group and Results Plus.
17 | Exam Result Print |  
18 | Print Certificate |  
19 | Teacher Exam Group Results | Exam uploads for a Teacher's Exam Groups.
20 | Exam Group Report | All below reports:
21 | Summary Teacher Report | "High-level summary View of all Exam Groups"
22 | Exam Group and Skills Summary Report | View of all exams taken in an Exam Group and a summary of the skill set scores for each exam.
23 | Exam Group Report | View of all exams taken in an Exam Group.
24 | Student View and Skills Summary Report | View of all students in an Exam Group, their exam scores, and a summary report of their skill achievements for each exam.
25 | Student View Report | View of all students in an Exam Group and their exam scores.

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
This was an extra feature that we did since the **Custom Reports** wasn't finished yet, but since the  **Custom Reports** is already done, we are not supporting this.
