### ISSUE TITLE
State/Province at Create New Testing Center Form

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#362]
The "State/Province" field in the "Create New Testing Center Form" cannot accept any entries. 
![image](https://user-images.githubusercontent.com/11155105/47088733-d55d0200-d227-11e8-9958-373d28284a62.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

It is very important.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, confirm and close

**Comment by HeshamHassan** [comment]
Done
