### ISSUE TITLE
Activity Log Appearance

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#363]
Activity Log Appearance needs to be adjusted.
![image](https://user-images.githubusercontent.com/11155105/47088859-1f45e800-d228-11e8-902f-a1b3c4b5633c.png)

**Comment by mahmoud-hussien1** [comment]
PR  - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/72/issue-363-fix-bug-in-activity-log/diff

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Check and confirm.

**Comment by HeshamHassan** [comment]
The page looks harmonic structure.
There is another point. 
- [x] The date column format. it must be in the format of: **yyyy/MM/dd, hh:mm:ss.00**
It will not be useful to acknowledge me that the change happened 3 weeks ago or 3 years ago. 
We use it to solve problems. So it must be accurate date and time.
![image](https://user-images.githubusercontent.com/11155105/48185929-94986a80-e347-11e8-840e-b25e2619736c.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
Done.
