### ISSUE TITLE
Test Search Tab

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#364]
Test Search tab appears in HTML code and needs to be adjusted.
![image](https://user-images.githubusercontent.com/11155105/47088939-5a481b80-d228-11e8-94d2-715dd4dec91c.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Give more elaboration.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Check the contents in the "Body" column.
http://skilledmatrix.com/admin/tests/10/questions/search

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/70/issue-364-strip-tags-in-search/diff

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Confirm fixed.

**Comment by HeshamHassan** [comment]
Done.
