### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#365]
@ahmedelbougha the format and spacing of the following pages need fixing even after I worked on fixing them

http://skilledmatrix.com/About-Us/Mission-and-Core-Values 
http://skilledmatrix.com/Skilled-Matrix-Solutions
http://skilledmatrix.com/Skilled-Matrix-Solutions/Testing-and-Advisory-Services

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please check this?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
any update?

**Comment by Ali-Galal** [comment]
@ahmedelbougha I will update you at the end of today or tomorrow maximum

**Comment by Ali-Galal** [comment]
@LamiaSalah Hesham fixed it, kindly check it and confirm

**Comment by LamiaSalah** [comment]
@Ali-Galal the first two pages are fixed without the photos and the third still have a formatting issue.
