### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#366]
* When I login with any role, I find a strange page: 
![image](https://user-images.githubusercontent.com/11155105/48051776-16a55980-e1b7-11e8-9a84-ef41016e5a29.png)
I tried login with more than 5 deferent browsers.
* Each time I get a deferent picture.
* The URL is: http://skilledmatrix.com/admin/cms/page/browse?path=%2Fhome%2Fskilledmatrix%2Fpublic_html%2Fuploads%2FPages%2Fmultimedia%2F2018%2F6%2F13%2F5b20e0b4add883e5188a96742864042ae170e202ee1ac.jpeg.jpg

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, please confirm and close.

**Comment by HeshamHassan** [comment]
Done

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 

![image](https://user-images.githubusercontent.com/11155105/50397584-95178400-0782-11e9-99c2-a6789879edf3.png)

Please recheck this issue. It was solved and the same issue happens agian since yesterday.
** Check the date at the right bottom corner.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
working on this

**Comment by MuhammedMahdy** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
