### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#370]
Contact Us page does not exist.
![image](https://user-images.githubusercontent.com/11155105/49340249-6fe59900-f64e-11e8-9164-9851d61824dd.png)

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 

what should appear at this page , contact us form ? if yes can you please send more details about required fields ?

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
Kindly advice.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  yes, as per the attached 
![image](https://user-images.githubusercontent.com/37042927/50154630-89cfde80-02d2-11e9-9965-2cf728992aeb.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 
will include this as new feature,so please confirm to start with it.

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly advice.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @LamiaSalah 
this issue duplicated please close,

**Comment by HeshamHassan** [comment]
Closed as Duplicated. 
The new issue is #379
