### ISSUE TITLE
Create Form Exam

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#371]
When clicking on Save button, error message appears:
![image](https://user-images.githubusercontent.com/11155105/49727155-a2137e00-fc80-11e8-9d44-1e06633c6aff.png)
..
![image](https://user-images.githubusercontent.com/11155105/49727178-ad66a980-fc80-11e8-8e79-d68fc4435b47.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha
Done! we add validation for the date please confirm about this and close i think this issue repeated  please confirm and close

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Would you change the date format to be able to enter and watch the date as normal ((dd-mm-yyyy))?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 

i just remove cache (autocomplete) in the expiration date , also we have to keep all system using the same date format

please check and close

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
> we have to keep all system using the same date format

You are right. But we can have a number mask for the user interface. So the user can see the date as logic as he used to see.

**Comment by HeshamHassan** [comment]
I'm collecting them and will send to you.

**Comment by HeshamHassan** [comment]
As agreed in the meeting between @mohamedMahdyCc and @HeshamHassan today..
This issue is moved to a new one.
- Create Exam Issue, is: #385
