### ISSUE TITLE
Create Appointment Page Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#372]
When creating an appointment, there is a picture placeholder for each exam.
- [x] How can I add or assign these pictures?
![image](https://user-images.githubusercontent.com/11155105/49736751-0263e900-fc9c-11e8-84b5-84bcb2dc5246.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 

Unfortunately, no way to edit or add exam test picture from admin panel
its just static image, if you wanna add this feature as `change request` please let me know

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly Advice!

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc remove the picture from this view.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
