### ISSUE TITLE
Create Exam

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#374]
When saving a new exam, the "Issue Happened" message appears. 
Kindly check it URGENT.
![image](https://user-images.githubusercontent.com/11155105/50053878-033dc480-014d-11e9-9946-e8effe2f871a.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
