### ISSUE TITLE
Website access

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#376]
@ahmedelbougha please make the website under construction as we did with SBP at the soonest

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc please remove the line Skilled Matrix a business and soft skills training solutions and delete the social media icons

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc Confirmed
