### ISSUE TITLE
Question mark icon

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#377]
@mohamedMahdyCc all paged have a question mark icon on the photo as attached 
![image](https://user-images.githubusercontent.com/37042927/50089127-9dfdd800-020d-11e9-8c67-e5c1914b9b07.png)

also, this page http://skilledmatrix.com/admin/cms/pages/21/edit  has a formatting issue with the text and background is grey

**Comment by HeshamHassan** [comment]
![image](https://user-images.githubusercontent.com/11155105/50225207-e86b8a00-03b0-11e9-9ed3-72d4a8676f1b.png)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@confirmed
