### ISSUE TITLE
Test Center Details Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#378]
- [x] CR File Download is not working.
- [x] Location map is missing.

![image](https://user-images.githubusercontent.com/11155105/50273858-db9c7400-044c-11e9-9c2b-7fea5770e56d.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal @ahmedelbougha @LamiaSalah 
Working on this ...

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
