### ISSUE TITLE
Upload Image from CK Editor

### ISSUE THREAD

**Issue by mohamedMahdyCc** [camelcasetechsd/testing-engine#380]
when upload image from ck editor not appear in server images list

**Comment by MuhammedMahdy** [comment]
@ahmedelbougha @Ali-Galal @LamiaSalah  

the images already uploaded , but not arranged , please try to upload an image with a solid color to confirm that it working fine.

please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc as discussed, having the photos not arranged is an issue, please ensure it's fixed. It's a waste of time to go through all the uploaded photos to find the newly uploaded ones.

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc as discussed, having the photos not arranged is an issue, please ensure it's fixed. It's a waste of time to go through all the uploaded photos to find the newly uploaded ones.

![image](https://user-images.githubusercontent.com/40764593/51111663-603ca100-1805-11e9-9e56-b875963e19ff.png)

i think this issue already fixed , at this screen shot i uploaded the first 2 photos just for testing, when upload new photo the sorting show them at the top (Descending sorting)

please check again and close if you see it done

**Comment by LamiaSalah** [comment]
Done
