### ISSUE TITLE
Search in Pages - Backend

### ISSUE THREAD

**Issue by mohamedMahdyCc** [camelcasetechsd/testing-engine#381]
search in pages with page title

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc agreed, with page title through all pages

**Comment by HeshamHassan** [comment]
Can we search with any word in the active section of the backend and the search result would be the page title for the page that contains the concerned search words?

**Comment by mohamedMahdyCc** [comment]
> Can we search with any word in the active section of the backend and the search result would be the page title for the page that contains the concerned search words?

@LamiaSalah @HeshamHassan 
ok waiting for approval...

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc, please advise on the status

**Comment by Ali-Galal** [comment]
rejected at mean time
