### ISSUE TITLE
table style in page preview 

### ISSUE THREAD

**Issue by mohamedMahdyCc** [camelcasetechsd/testing-engine#382]
please try to edit page `Program Options` in cms > pages - page `9` and click `preview` you will seen the table without border

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please ensure this is applied in general and not for specific pages , so we don't face this issue each time we create a table

**Comment by MuhammedMahdy** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc could you please send me the page link to check?

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  Done
