### ISSUE TITLE
Broken Link in a Page

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#384]
This page: http://skilledmatrix.com/About-Us/The-Skilled-Matrix-Advantage
has links which are not working: 
- Authorized Certification Centers
- Educators

![image](https://user-images.githubusercontent.com/11155105/50582438-aa239f80-0e73-11e9-9aa9-3d130d67ae6c.png)

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan this is not issue.
the link pointing on static page whose Path changed from admin **CMS > Page** Section.
when you change  any **static page path**, please change it in all places that use that page's path.

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
Kindly check and advice.

**Comment by LamiaSalah** [comment]
@HeshamHassan links edited now, but I can't check as there's an issue with the preview option on the website

**Comment by HeshamHassan** [comment]
Broken Links issue is solved.
Page Preview in CMS is in a separate issue #387
