### ISSUE TITLE
Create Exam Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#385]
- [ ] Change the date format to be able to enter and watch the date as normal as users know ((dd-mm-yyyy))

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan please let us in which pages you want to apply this Enhancement ?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
- Create appointment 
- Reschedule appointment
- User profile form:  Date of birth
- Testing center form:  CR Expiration date
- Create/Modify test:  Expiration date
- Create vouchers:  Expiry Date

**Note:**
Show the date as needed in the system. But let the user inputs the date starting with day then month ends with the year.
Otherwise, make it chosen with the date bicker as you did in the page of "create new test" form.
