### ISSUE TITLE
Page preview not working

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#387]
@mohamedMahdyCc there's an issue with the page preview for all pages. I get a message that it's not working

**Comment by HeshamHassan** [comment]
![image](https://user-images.githubusercontent.com/11155105/50734934-d9aa1300-11b7-11e9-83bb-25892d0d3ab3.png)

![image](https://user-images.githubusercontent.com/11155105/50734941-de6ec700-11b7-11e9-84c9-777398f708da.png)

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc please advise

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Fixed! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  confirmed
