### ISSUE TITLE
Date Fields Autocomplete Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#388]
Remove cache (autocomplete) from all date fields.
- [x] Create appointment 
- [x] Reschedule appointment
- [x] User profile form:  Date of birth
- [x] Testing center form:  CR Expiration date
- [x] Create/Modify test:  Expiration date
- [x] Create vouchers:  Expiry Date

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
This field does not act right... It still chaching and it is date field and caching from username!!!!!
- [ ] User profile form: Date of birth
![image](https://user-images.githubusercontent.com/11155105/51246149-ba229f80-199a-11e9-885e-dd9fca431a9a.png)

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc update?

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
