### ISSUE TITLE
menu tabs

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#389]
@mohamedMahdyCc all the tabs at the menu are not see, only Skilled Matrix Solution is available

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Not yet!!

**Comment by HeshamHassan** [comment]
Done.
