### ISSUE TITLE
Test Duplicate Button

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/testing-engine#391]
- Add duplicate button for the test. It will do:
  - Duplicate the test.
  - The second copy test will have the whole question with its model answers.
  - The second copy test will be editable like as any new test till delivering it.

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc @ahmedelbougha update us, please

**Comment by mohamedMahdyCc** [comment]
@Ali-Galal @ahmedelbougha 
- did you will need to add duplicate button for questions ? 
- did you will want to save this operation to activity log so the admin can know whose copied the test ?

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc No, I dont need duplicate question in mean time.
yes, every single action should be registered in the log

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc update us, please

**Comment by mohamedMahdyCc** [comment]
@Ali-Galal @ahmedelbougha 
**Estimation: 9 days**

**Comment by Ali-Galal** [comment]
declined
