### ISSUE TITLE
Links format does not show on Frontend 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/testing-engine#394]
@mohamedMahdyCc when creating a link in any internal page, it appears to be underlined and blue, while in the frontend it appears like the rest of the text, it does not appear as a clickable link 

e.g: http://skilledmatrix.com/Partner-Programs/Authorized-Testing-Centers 
http://skilledmatrix.com/Partner-Programs/Corporate-Testing-Centres

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
When moving over any link the link change its color. But when clicking on it its color changes to black and be the same as other page fonts.

**Comment by MoatazAbdAlmageed** [comment]
@HeshamHassan I think now works well I tested http://skilledmatrix.com/Partner-Programs/Authorized-Testing-Centers

**Comment by MoatazAbdAlmageed** [comment]
@HeshamHassan @LamiaSalah  I think you have to update links in http://skilledmatrix.com/Partner-Programs/Corporate-Testing-Centres

**Comment by LamiaSalah** [comment]
@MoatazAbdAlmageed Confirmed
