### ISSUE TITLE
TE-6: Simple Admin Dashboard

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#6]
Points: 1
Estimated Time: 0.5 days
Actual Time: -

∘ /admin homepage contains links to modules 3 box grid
∘ side menu getting that from configuration array in php file

**Comment by babanesma** [comment]
I didn't create a side menu , I didn't find a suitable plugin yet so I added the menu to the main navigation in the header

**Comment by ahmedelbougha** [comment]
QA - Done
