### ISSUE TITLE
TE-69 : Various Issues 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#69]
## Various issues reported from the client 
* [x] "Birth City / Province * When I save this page and this field in empty is saved without any message alert."  http://testing-engine.camelcasetech.com/admin/users/1/edit
* [x] View user form I need back button   http://testing-engine.camelcasetech.com/admin/users/1
* [x] Date of birth should be at least 10 years old   http://testing-engine.camelcasetech.com/admin/users/create
* [x] I can’t delete any roles, I need delete button  http://testing-engine.camelcasetech.com/admin/users/roles
* [x] Commercial Name (non-English) shouldn’t be mandatory    http://testing-engine.camelcasetech.com/admin/testing-centers/create
* [x] Text label for Owner national id field is Owner Name (non-English)  http://testing-engine.camelcasetech.com/admin/testing-centers/create
* [x] Owner Name (non-English) shouldn’t be mandatory http://testing-engine.camelcasetech.com/admin/testing-centers/create
* [x] When I save testing center form I faced error   http://testing-engine.camelcasetech.com/admin/testing-centers
* [x] Add back and rest button into roles page    http://testing-engine.camelcasetech.com/admin/users/roles
* [x] We need the Duration customize  http://testing-engine.camelcasetech.com/admin/tests/create
* [x] When I select duration H=00 & M=00 is not allowed   http://testing-engine.camelcasetech.com/admin/tests/create
* [ ] Disable parent category

**Comment by badr4php** [comment]
Roles can be soft deleted so admin can restore it except 'Super Admin' can't be deleted.

**Comment by babanesma** [comment]
@ahmedelbougha All issues are resolved except the following 
- I can’t delete any roles, I need delete button ( please check mohamed's [comment](https://github.com/camelcasetechsd/testing-engine/issues/69#issuecomment-271854553) )
- Disable parent category ( needs client decision )

**Comment by ahmedelbougha** [comment]
@babanesma @badr4php 
for roles please make it hard delete beside the soft delete
