### ISSUE TITLE
TE-7: Roles Entity (TE-4)

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/testing-engine#7]
Related to #4 

- [x] Role Entity
- [x] Role Factory
- [x] Role Migrations

**Comment by babanesma** [comment]
- [ ] Role Entity should extend `Illuminate\Database\Eloquent\Model` rather than `Illuminate\Foundation\Auth\User` 
- [ ] Role Factory function is not completed in database\ModelFactory.php
- [ ] please correct the comments in role_user migration file
