### ISSUE TITLE
TE-74 : Roles Privileges

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#74]
### Description 

> #### 1. Test Taker
> **Description ​ :**
> This is the user who will schedule the tests he will be taking in the workstations
> available for each test center, and then go physically to the workstation to perform the test.
> 
> **Access:**
> - He/She can view a list with all the public published tests by the test centers.
> - He/She can filter this list based on the test center which provides the test , the skills he wants to test or to be certified , or the nearest workstations to him.
> - He/She can view each test details like price , date available , duration and the workstations in which this test is available.
> - He/She can schedule for a test to be taken in any workstation available for this test , he should pay for the test price before completing this step .
> - After successful payment he can view the details of the payment , and the details of the workstation and the test center administrator who will control the test . 
> - According to the appointment scheduled , the test taker should physically be presented in the workstation that he picked during the date and time he also picked . Then he can perform the test in the allowed duration of the test that should be set from the website.
> - During the test, the test taker should see an on-screen clock showing a countdown of the test duration .
> - After “End of the Test”, the system must encrypt answers and communicated back to the server
> 
> #### 2. Test Center Administrator ( TCA )
> **Description:**
> This is the user who will be fully responsible on the test center and its workstations .
> 
> **Access:**
> - The TCA can create test center.
> - The TCA will be able to add workstations, set their addresses, code and their ip addresses. These information should approved by the TEM.
> - The TCA will be able to assign TCP to each workstation.
> - The TCA can view reports on each test , each workstation and each TCP .
> - The TCA will have access to a page that lists all the appointments along with their statuses in a calendar view
> 
> #### 3. Test Center Proctor ( TCP )
> **Description:**
> This is the user and he/she will be physically be presented during the test
> appointment scheduled by the test taker in the workstations.
> 
> **Access:**
> - The TCP can be assigned by the TCA to any workstation.
> - The TCP can change the workstation he is assigned to.
> - During the test, TCP must be able to mark any workstation and file an automated “Irregularity Report”. And in this case, the system must show the score result as
> “Failed” and attaching the Irregularity Report in the score report.
> 
> #### 4. Test Engine Manager (TEM)
> **Description:**
> This is the user who can control over organizations , tests , test centers and users
> 
> **Access:**
> - The TEM and only the TEM , will have access to the ​ admin modules ​ .
> 
> #### 5. Test Provider Manager (TPM)
> **Description:**
> This is the user who will manage the test provider like Microsoft , Oracle ... He/She will be responsible for entering the exams or certifications provided by his entity.
> 
> **Access:**
> - The TPM will provide the tests available by his entity.
> - The TPM should provide the blueprint and the bank of questions for each exam.
> - The TPM can request voucher ( eligibility codes ) for each exam and this should be
> approved by admin ( TEM ).
> - The TPM can provide tutorials for exam.
> - The TPM can import his exams to the system directly ( ​ each import process should be asked in a different change request )
> - The TPM can provide references for each exam , and set their availability for the exam taker through the exam
> - The TPM should assign the availability for the tools menu ( Scratch pad , calculator ...) for each exam.
> 

### SubTasks 
- Make sure all roles access are fulfilled 
- Add the missing privileges for the roles in `/database/seeds/RolePrivilegesSeeder.php` 
- Unit Testing all roles access

**Comment by babanesma** [comment]
@badr4php 
- unit testing of `TEMRoleAccessTest` is failing on line 53 
- try to separate each use case in a separate test method , for example : 
  - testTEMCanVisitDashboard
  - testTEMCanVisitSettings 
  - ...
- apply the above note on the other tests : 
  - `TCARoleAccessTest` 
  - `TPMRoleAccessTest`
  - `TestTakerRoleAccessTest`

**Comment by badr4php** [comment]
- [x]  TCA  can't activate labs ,he must have permission to activate them.

- [x] Error when create a workstation for inactive lab.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/129
