### ISSUE TITLE
TE-88 : Bugs / Issues - 9 Mar 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#88]
- [x] Admin General 
  - add back button to edit/create/view pages to return to module listing page 

- [x] Users
  - Cities should have readable text 
  - reminder question / reminder answer / confirm should be required 
  - drop down menu for phone country code 

- [x] Roles
  - remove back button from listing page 

- [x] Testing Centers
  - Non english name should not be required 
  - Cities should have readable text 
  - drop down menu for phone country code 
  - button to remove added TCA TCP selected 
  - add helping text beside the map 

- [x] Reports
  - print report functionality : print button to print the whole report without the layout 
  - export report functionality : export button to export the report results to results 

- [x] Registration 
  - disable copy/paste in these 3 fields ( confirm email , password & confirm password )
  - replace google captcha by recaptcha ( letters and numbers )
  - successful registration is returning to the same page 

- [x] Tests
  - tags should not be mandatory 
  - error code when creating new test ( missing screenshot and stack trace )

**Comment by badr4php** [comment]
Task was finished except this point "replace google captcha by recaptcha ( letters and numbers )"

**Comment by babanesma** [comment]
@badr4php 
- Testing Centers 
  - enlarge the input field of Admins and Proctors and only expand its lines when it has more users than it can fit in one line 
- Apply the same component into Tests tags and

**Comment by babanesma** [comment]
@badr4php revert users/roles form to the old one

**Comment by babanesma** [comment]
@badr4php 
regarding the back button you have added in all modules , it is using `URL::previous` , depending that every time you are editing or adding a new entity you will go through the same process ( open the listing > then add a new user or edit user ) , while the if I access the edit URL directly ( /admin/users/1/edit ) and hit back button , it will redirect to the home page while it is not required 

Please change `URL::previous` to the dedicated listing page of each module

**Comment by badr4php** [comment]
Last comment was applied

**Comment by badr4php** [comment]
That is the requirement : disable copy/paste in these 3 fields ( confirm email , password & confirm password ) so We need to  disable copy/paste in 'confirm email' field instead of email field .

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/106
