### ISSUE TITLE
TE-95 : Tests Module changes ( TE-89 )

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#95]
- remove the part in the form of the Tests that picks the available test centers 
- add new form accessible from the details page of the testing center ( /admin/testing/<id>/tests ) 
- the form will be accessible only for TCAs and super admin 
- The TCA should select the provider first , then a list of tests provided by this provider will appear from which the TCA can choose and add the test to be available for his testing center
- no DB changes will be made as the same relationship applies but only the forms will differ
- apply needed changes in unit testing

**Comment by babanesma** [comment]
@badr4php 
- in the tests adding form ( `/admin/testing-centers/1/tests` ) when there are no tests with this provider , output an error message to the user saying there are no tests with this provider

**Comment by AbdElmoneimMohamed** [comment]
## QA tests
@badr4php 
- [ ] TCA can add test to testingCenter until hes not  admin  on it.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/102
