### ISSUE TITLE
TE-96 : Drag / Drop question ( TE-89 )

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#96]
![img_20170328_113957](https://cloud.githubusercontent.com/assets/2117734/25001494/130fc032-2046-11e7-831f-b1c1589a8d33.jpg)

**Comment by babanesma** [comment]
@AbdElmoneimMohamed 
Avoid duplicating uploaded files into 2 places while creating model answers ( modules/admin/Tests/Models/ModelAnswers.php::uploadMultimediaFile ) , but make the desktop app grabs the photos of the exam when it starts

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 
- [x] when creating the model answers of drag and drop questions the multimedia must be required

**Comment by badr4php** [comment]
PR - https://git.camelcasetech.com/camelCase/testing-engine/pulls/124
