### ISSUE TITLE
TE-97: SPIKE - Calendar Fields ( TE-89 )

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#97]
Spike for 1 hour to investigate 
==
check every date field in the forms and make sure it is working on Firefox , Chrome and IE 

- Check all modules frontend and admin 
- unify the way the calendar appears

**Comment by AbdElmoneimMohamed** [comment]
- Date Fields in admin module
   * date of birth in user model
   * CR Expiration date field in testingCenter model
   * start time and end time in testingCenter model
   * expiry date in vouchers creation
- Date Fields in frontend module
   * date of birth field in profile model 
   * schedule date field  in test model

we can use  https://jqueryui.com/datepicker/ to make the date field working fine on Firefox , Chrome and IE
