### ISSUE TITLE
TE-98 : Emails ( TE-89 )

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#98]
- [x] create new module ( /admin/settings/emails ) accessible by super admin only 
- [x] the new entity will have the following attribute 
  - id
  - title
  - code ( no-spaces , all capital letters )
  - template 
- [x] This will only change the template of the email to be stored in the database 
- [x] Seed all the emails and existing emails from the attached document 
- [x] Apply all triggers from the attached document 

[Test Engine Notification Emails.docx](https://github.com/camelcasetechsd/testing-engine/files/854454/Test.Engine.Notification.Emails.docx)

**Comment by badr4php** [comment]
Pleas provide more details about this points :-
1-  Incident  (if applicable, joining with Exam Result email)
2- send emails when editing modules. 
[Test.Engine.Notification.Emails.pdf](https://github.com/camelcasetechsd/testing-engine/files/879589/Test.Engine.Notification.Emails.pdf)

**Comment by babanesma** [comment]
@badr4php 
- Email code can still be editable if we removed "readonly" attribute from the html , make it only appears as static text 
- change email codes to have underscore between each word ( like `CREATE_NEW_SETTINGS_OPTION` instead of `CREATENEWSETTINGSOPTION` ) 
make that in new migration
